### ISSUE TITLE
Feature-Request: Meta-Morphism corresponding to Meta-theories

### ISSUE THREAD

**Issue by Jazzpirate** [UniFormal/MMT#14]
We will need this in the long run. In MMT paper we discuss this.

**Comment by kohlhase** [comment]
Florian thinks that we need to include a meta-view in the view. This is partially realized in the code.

**Comment by florian-rabe** [comment]
I've gone back and forth on whether it's useful to make a meta-morphism explicit in structures/views.

It's not really needed because one can simply include the meta-morphism into the structure/view.
