### ISSUE TITLE
mmt.api.utils.MMTSystem incompatible with jEdit Plugin

### ISSUE THREAD

**Issue by Jazzpirate** [UniFormal/MMT#141]
on start:
java.lang.NullPointerException
at info.kwarc.mmt.api.utils.MMTSystem$.runStyle$lzycompute(System.scala:38)

Trying to hack around it yields "no backend available" messages for literally every symbol not in local scope (e.g. all of LF) (tried thin jars with path to jEdit-settings/jars)

**Comment by Jazzpirate** [comment]
turns out, the problem was that
1. I finally had to actually set up MMT
2. the field "custom folder that contains archives" in the jEdit settings menu now does nothing. I suspect that "custom startup msl file" also does nothing. So I suggest either making it do something or getting rid of it.

**Comment by Jazzpirate** [comment]
nope, that wasn't it - I currently have no idea where jEdit wants the archives to be (or which mmtrc is used) - the corresponding field in the settings menu seems to do nothing.

**Comment by cmaeder** [comment]
I could reproduce 

```
11:29:46 [main] [error] PluginJAR: java.lang.NullPointerException
11:29:46 [main] [error] PluginJAR:  at info.kwarc.mmt.api.utils.MMTSystem$.runStyle$lzycompute(System.scala:38)
```

after `mmt.jar :jeditsetup install`. It works, however, for the master branch, that does not include
https://github.com/KWARC/MMT/commit/cf3cc3b28844ec4e7b1989d1284a9eb849baeca1

**Comment by Jazzpirate** [comment]
do you happen to know, where the jEdit plugin looks for archives by default? I currently have no idea how to point it to my archives folder...

**Comment by cmaeder** [comment]
not really. My created file `.jedit/plugins/info.kwarc.mmt.jedit.MMTPlugin/mmtplugin.log` contains:

```
backend: /home/maeder/.jedit/plugins/info.kwarc.mmt.jedit.MMTPlugin/mars is not an archive or a folder containing archives
```

**Comment by cmaeder** [comment]
In my eyes this is a blocker for merging mirror-svn into master. (I'm working on it.)
