### ISSUE TITLE
give access to the full/raw error log in the error viewer

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#144]
That would be very useful. Either as the raw error view or as the full XML error file; probably both, you could just add the two links at the end of the short error message as "error file (raw) (xml)". 

 @m-iancu's error viewer has the very nice "source with errors annotated" feature, maybe that could be integrated here?

**Comment by cmaeder** [comment]
You get the full xml error by clicking on "error" (or "warning") within the "level" column. Is this not enough? The whole file - that I showed a while ago - seemed to be too much. Or do you want a link to the `.ltxlog` file that would be latexml specific?

**Comment by kohlhase** [comment]
at least in the latexml case having access to the pdflog would be very helpful. Because I often have to see what libraries were loaded, ...

**Comment by cmaeder** [comment]
Right, that would be specific to the `pdflatex` target.

**Comment by lambdaTotoro** [comment]
Do we still want this for the `pdflatex` target, @kohlhase ?

**Comment by kohlhase** [comment]
no, the error viewer is not operational any more
