### ISSUE TITLE
standalone build system (lmh bindings?)

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#147]
I am gearing up to do some 
- LaTeXMLsTeX development on a branch,
- more source develop on the sTeX Problems
  and therefore I would like to have the build system run locally for me.
  The missing piece seems to be the error viewer. Can we integrate this into lmh (and the lmh docker)?

This should not be that difficult right? 

cc: @angerhang @m-iancu @tkw1536

**Comment by cmaeder** [comment]
see #111
