### ISSUE TITLE
Make a better logo

### ISSUE THREAD

**Issue by tkw1536** [UniFormal/MMT#174]

**Comment by jbetzend** [comment]
I saw that this issue was open and I got bored on the train today so here is my doodle.
The different shapes represent foundation independence! :-P

I think the letter spacing seems a bit weird but if you move them around, they're not the same size / Y-position anymore. Any thoughts?

![mmt_logo_idea_1](https://cloud.githubusercontent.com/assets/1606110/22565991/8ea0e43a-e98a-11e6-84f5-e3e176346941.png)

**Comment by jbetzend** [comment]
And here's a second version, a little tweaked. Also, square, for thumbnailing purposes.

![mmt_logo_idea_2](https://cloud.githubusercontent.com/assets/1606110/22569814/3bb05d46-e999-11e6-9585-9f50fcc085c3.png)

**Comment by tkw1536** [comment]
Great work! Looks a lot better than what we currently have.

**Comment by jbetzend** [comment]
Thanks. Who do we bug about installing it?

**Comment by tkw1536** [comment]
As with everything else MMT, it should go through @florian-rabe

**Comment by florian-rabe** [comment]
I like it if has a meaning.

In the old logo (which I literally did in MS Paint, so I don't mind it being replaced), the vertical arrangement symbolizes the two meta-levels that we put on top of the usual theory, and the arrows symbolize the use of theory graphs at every level.
I like that.

Another potential motivation for symbolism might be the 4x4 arrangement of domains and solutions that describes UniFormal (see http://uniformal.github.io/).

The word UniFormal itself might also inspire a nice logo.

**Comment by kohlhase** [comment]
I like "meaning" in logos as well, and I rather liked the old logo idea as well, just that it was so badly executed. 

> Another potential motivation for symbolism might be the 4x4 arrangement of domains and solutions that describes UniFormal (see http://uniformal.github.io/).

you realize that this is essentially the tetrapod "meaning", right, and as much as I would like to have a tetrapod logo for uniformal, that would be a bit of a land-grab, which might aggravate our partners.

**Comment by florian-rabe** [comment]
Tetrapod needs a logo, too, doesn't it?
Any good logo ideas in that direction can be donated.

**Comment by jbetzend** [comment]
So, what is the stance on this?

If there are any changes that you would like to the logo, Id be happy to throw up GIMP again, just let me know.

**Comment by florian-rabe** [comment]
I'm not very good at artsy stuff.

I think my general idea is already pretty nice: it symbolizes both the meta-levels and theory morphisms - two of the most important aspects of MMT.

The main thing that's needed is to make it good-looking (higher resolution, more colors, etc.).

If there's a different idea that can also symbolize the system integration and universality aspects as well, that would be even better.

**Comment by jbetzend** [comment]
So, "No" on the one above? I can see if I can whip something else up.

**Comment by kohlhase** [comment]
I also like the three-arrows logo, if it were a real logo.

**Comment by kohlhase** [comment]
We should redo Florian's logo in SVG and use that from now on.

**Comment by jbetzend** [comment]
Okay, I'll get on this for Release 9. 

@kohlhase @florian-rabe I have one more suggestion. Do you want simple straight arrows like in the original or should we use squiggly / hooked arrows, too? You know, like we have in the theory graphs. Picture for comparison.

![mmt_classic_ideas](https://user-images.githubusercontent.com/1606110/33612747-e0f8147c-d9d2-11e7-807a-4d308487a9be.jpg)

**Comment by kohlhase** [comment]
I prefer the left one. include, structure, view are the main relations. A pity that the meta relation is not in there. But maybe that could be a dotted vertical down arrow.

**Comment by jbetzend** [comment]
How are these for a start? Theresa had the idea of using the original TeX MMT Theory Graph Arrows. The colours were Michael's idea.

![new_mmt_logo_with_colours_rendered_for_github](https://user-images.githubusercontent.com/1606110/33663592-e7761ec0-da90-11e7-8d61-a14c8f4fd302.png)                       ![new_mmt_logo_without_colours_rendered_for_github](https://user-images.githubusercontent.com/1606110/33663600-ed48ccc6-da90-11e7-9d53-fc1af3370f67.png)

I created the images using [this LaTeX Viewer](http://www.tlhiv.org/ltxpreview/) and [this code](http://pastebin.tlhiv.org/X65W8zz8).

The files above are small PNGs so they can be displayed here. The SVGs themselves are attached: [new_MMT_logo.zip](https://github.com/UniFormal/MMT/files/1535272/new_MMT_logo.zip)

**Comment by florian-rabe** [comment]
Unfortunately, we've never properly standardized the arrow styles and colors.
I'll start an issue for that.

Technically, plain arrows subsume all arrows.

**Comment by florian-rabe** [comment]
Following up on this development, what kind of big logo we can design, e.g., as the focus of a main web page?

**Comment by jbetzend** [comment]
For comparison, here's a version with only morphism arrows:

![boring_logo](https://user-images.githubusercontent.com/1606110/33715217-16e78254-db52-11e7-8981-80a7139c8756.png)

And here is one with the generic LaTeX arrows:

![boring_logo_generic](https://user-images.githubusercontent.com/1606110/33715383-91ceba1e-db52-11e7-8597-e5fe1de88b62.png)

I think these are pretty boring though, "general" or not. I don't think we should use either of those.

**Comment by kohlhase** [comment]
I like the version with the three different arrows much much better. And I have a (slight) preference for colors.

**Comment by florian-rabe** [comment]
Would sans serif font look better?

**Comment by jbetzend** [comment]
Here's the same thing in sans serif (derived by adding the `[font=\sffamily]` parameter to the tikzpicture).

![new_mmt_logo_colours_sans_serif](https://user-images.githubusercontent.com/1606110/34160427-3460967a-e4cd-11e7-98d6-b5ce07d7c728.png) ![new_mmt_logo_bw_sans_serif](https://user-images.githubusercontent.com/1606110/34160504-84fcd224-e4cd-11e7-8963-d75e0166b957.png)

I think the serif fonts look a lot better in context. Especially with colours, the sans-serif font looks a little childish if you ask me. Also, standard mathematical notation in LaTeX uses serifs, I think we're better off with that.

**Comment by kohlhase** [comment]
We have decided to use the left one, only with the red and blue colors switched. 
They will be deployed to MMT/scripts (Michael will do that) and also put the PGF/tikz libraries there under MMT/sty there.

**Comment by kohlhase** [comment]
Tom will do generation of the files 
logo location for icons: src/mmt-api/resources/mmt-web/mmt.png
via an sbt target.

**Comment by jbetzend** [comment]
¯\_(ツ)_/¯

**Comment by kohlhase** [comment]
The TeX and a Makefile are committed off to Tom.

**Comment by kohlhase** [comment]
I think this is done. Now we only need to install it everywhere.

**Comment by jbetzend** [comment]
In the future, please refer to the SVG in [the gl.kwarc resources repository](https://gl.kwarc.info/kwarc/resources/tree/master/mmt-logo). The code above generates an SVG with a slight transparent border that is also not perfectly square.

Both issues have been fixed (by poking inkscape until it did what I wanted, hence no updated code here) in the version in the resources repository.
