### ISSUE TITLE
Bug in LazyConstant

### ISSUE THREAD

**Issue by digama0** [UniFormal/MMT#177]
Although I haven't tested it, the logic in https://github.com/UniFormal/MMT/blob/master/src/mmt-api/src/main/info/kwarc/mmt/api/symbols/LazyConstant.scala appears to be reversed, only activating _after_ first use, and additionally the flags aren't even being set so the thunks will never run. Why not use a `lazy val` for this?

**Comment by florian-rabe** [comment]
I'll fix it.
