### ISSUE TITLE
Better handling of errors during startup

### ISSUE THREAD

**Issue by tkw1536** [UniFormal/MMT#187]
During recent debugging of MathHub I have found that a lot of time MMT simply crashes with one error during startup and then goes into an infinite loop of doing nothing until someone either kills the process or sends CTRL+C.  The most dominant cause of this I have seen is when a plugin fails to load because of ```java.lang.ClassNotFoundException```. 

MMT should do one of two things in this case:
1. Keep processing other directives in MSL or MBT files that were passed via command line (in particular turning on a web server)
2. Crash and exit with a non-zero code and not process anything else

**Comment by kohlhase** [comment]
cc: @florian-rabe @Jazzpirate 
A more stable startup would be something that is very very needed for MMT, given the recent MMT@MathHub problems. I think that this issue shold be given priority (but I cannot "vote" for it :-() you should probably allow that for non-project-members (like me).
