### ISSUE TITLE
mmt shell still announces svn

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#195]
the MMT shell starts up with 
```
This is the MMT shell.
See https://svn.kwarc.info/repos/MMT/doc/api/index.html#info.kwarc.mmt.api.frontend.Action for the available commands.
```
I am sure that this shoud be somewhere in http://uniformal.github.io now.

**Comment by tkw1536** [comment]
Fixed on devel with https://github.com/UniFormal/MMT/commit/17ab2b5ba62cd6de5dea2f0a9ff7618d24d83eb6
