### ISSUE TITLE
Proper documentation of available frontend commands

### ISSUE THREAD

**Issue by tkw1536** [UniFormal/MMT#198]
Currently the list of frontend commands simply refers to https://uniformal.github.io/apidoc/#info.kwarc.mmt.api.frontend.Action (that is the api documentation). 

There should be a list of basic commands provided in the prompt, optimally there should be a help command which simply prints a list of basic commands. Something along the lines of
```
This is the MMT shell.
Type 'help' for help, use 'exit' to exit. For a full list of available commands, see 
https://uniformal.github.io/apidoc/#info.kwarc.mmt.api.frontend.Action.
```

would be good.

**Comment by kohlhase** [comment]
the help should be generted from code. add a `tohelpstring` for all actions.

**Comment by florian-rabe** [comment]
We should add methods
class Action {
  def helpString: String
}
and
object Action {
  def allActions: List[Class[Action]]
}
to automatically generate an uptodate command list.

**Comment by tkw1536** [comment]
Fixed on devel, closing.
