### ISSUE TITLE
Update ```sbt install``` to run appropriate MMT code

### ISSUE THREAD

**Issue by tkw1536** [UniFormal/MMT#202]
Currently, the ```sbt install``` task runs custom code to install the jedit jars. Instead it should call code from within MMT, in particular it should be a custom run task (see  http://www.scala-sbt.org/0.13.5/docs/faq.html#how-can-i-create-a-custom-run-task-in-addition-to-run).

**Comment by florian-rabe** [comment]
Currently I use the target jedit/install, which runs custom code and works fine.
