### ISSUE TITLE
MMT license in conflict with Github Terms of Service

### ISSUE THREAD

**Issue by tkw1536** [UniFormal/MMT#206]
Since 28th of February, [Section D.5](https://help.github.com/articles/github-terms-of-service/#5-license-grant-to-other-users) "License Grant to Other Users" of the GitHub Terms of Service states:

> By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your  repositories [...]. 
>You grant each User of GitHub a [...] license [...] to use, display and perform your Content, and to reproduce your Content [...] on GitHub as permitted through GitHub's functionality. 

I would interpret this as allowing each user of GitHub to make a fork and distribute said fork through GithHub functionality. In particular this means they have the right to make "releases" on their fork, that is distribute binaries. 

This is in direct contradiction to the (current version of) the MMT license. I am not sure how to solve this issue, apart from switching to a license that allows these rights (i.e. GPL, BSD, etc). I understand the [reasoning](https://uniformal.github.io/doc/setup/license.html) for choosing not to give these rights, however I wanted to make an issue either way. 

/cc @florian-rabe @kohlhase

**Comment by kohlhase** [comment]
let's not worry our little heads about this for the moment. 

I am sure that the GitHub people (they have 500+ employees) will figure that out.

**Comment by tkw1536** [comment]
I am aware that this is not something that we need to solve right now. Still wanted to point it out and write down for future reference.

**Comment by kohlhase** [comment]
this is the same as #1
