### ISSUE TITLE
Some errors aren't caught "properly", causing issues in jEdit

### ISSUE THREAD

**Issue by Jazzpirate** [UniFormal/MMT#213]
Some errors, specifically those caused by ChangeListeners, aren't properly caught, resulting in jEdit hanging up or otherwise behaving unexpectedly with no information about what went wrong.

The reason seems to be that even though in StructureParser.scala (Line 93) the controller.add is in a catch-Environment (which passes them on to the proper errorCont), errors thrown by ChangeListeners are caught by the controller itself and handed on to it's reporter, which doesn't forward to jEdit, I guess.

In the long term we should probably thinking about using a different reporter during parsing, which passes errors on to jEdit.

**Comment by kohlhase** [comment]
partially fixed
