### ISSUE TITLE
Type checking result depends on memory, because reasons

### ISSUE THREAD

**Issue by Jazzpirate** [UniFormal/MMT#214]
If T depends on S and I build S before T (in the same session), T will type check. If you don't (and S is loaded from disk), it won't. Not quite clear why.

Example: 
T=MitM/smglom/algebra/modulsvectors.mmt 
S=MitM/smglom/algebra/ringsfields.mmt (once I've pushed the current state)

**Comment by Jazzpirate** [comment]
interestingly, I just noticed that the errors still appear shortly, before they disappear 0o

(in jedit; in intelliJ they just don't appear in the first place. Weird)

**Comment by Jazzpirate** [comment]
might have been solved a while ago... trying to reproduce at some point

**Comment by kohlhase** [comment]
fixed
