### ISSUE TITLE
Refactor mmt-js-api.js in Backend-Calls and Frontend functionality

### ISSUE THREAD

**Issue by tkw1536** [UniFormal/MMT#216]
Currently the [mmt-js-api.js](https://github.com/UniFormal/MMT/blob/master/src/mmt-api/resources/mmt-web/script/mmt/mmt-js-api.js) file is a mix between
* backend calls (to the MMT webserver) and
* frontend, jQuery-dependent, functionality. 

To be able to use this indendently, we should refactor it file and split it into two seperate files.

**Comment by kohlhase** [comment]
fixed
