### ISSUE TITLE
FromTheory syntax is not recognised by the linter

### ISSUE THREAD

**Issue by vv20** [UniFormal/MMT#224]
FromTheory syntax seems to be a useful and essential feature of the language, yet the typechecker fails it every time (including in existing archives like MitM/smglom on mathhub). Judging from the error message ("expected ':', '=', '#', '##', '@', found <identifier>), the linter tries to parse it as a constant definition instead of a different form of native syntax.

**Comment by Jazzpirate** [comment]
known and we're working on it (related to general overhauling of LFX/Records) :)

**Comment by Jazzpirate** [comment]
Fixed with new ModelsOf syntax
