### ISSUE TITLE
Includes of parametric theories

### ISSUE THREAD

**Issue by markuspf** [UniFormal/MMT#225]
If we have a theory `SubgroupsTheory` that depends on a group, and want to define a subtype `NormalSubgroups` then to use `ModelsOf` I have to do the following stunt:

```
normalSubgroupOf : group → type ❘ = [g] (ModelsOf `?NormalSubgroups/NormalSubgroupsTheory ) g g ❙
```

@Jazzpirate tells me that includes of theories with parameters should be "sorted out".

**Comment by kohlhase** [comment]
Is this done?

**Comment by Jazzpirate** [comment]
done, except for Florian's approval

**Comment by florian-rabe** [comment]
I've completely redesigned this now. It's now implemented up to minor bugs now.
