### ISSUE TITLE
Views that consider includes

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [UniFormal/MMT#228]
Hi there, 

I would like to do a view on sorting algorithms, where SortAlg and Quicksort are structurally the same:

view quicksortAsSortalg : ?SortAlg → ?Quicksort =
	sortingalgorithm = quicksort ❚
	sortalgsorts = quicksortsorts ❚
❚

but keep getting "no assignment found" errors on things that are included by both. 

It would be nice if MMT would look at the include hierarchy of views here.
 
Thanks already!

**Comment by Jazzpirate** [comment]
should be resolved by now...
