### ISSUE TITLE
Syntax in subtyping relations

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [UniFormal/MMT#230]
I noticed that, when listing parameters in MMT, this is parsed
`A : type, B : type, C : type, ac A <* C`
but this isn't
`A : type, B : type, C : type, ac : A <* C` .

Is it intended that there's no colon involved for things of type subtyping relation?

**Comment by kohlhase** [comment]
Theresa, best to assign things to one of the principals, to have more effect :-).

**Comment by Jazzpirate** [comment]
brackets
