### ISSUE TITLE
sbt compatibility issues

### ISSUE THREAD

**Issue by jbetzend** [UniFormal/MMT#231]
sbt recently had a [major version bump](https://github.com/sbt/sbt/releases) (from 0.13.6 to 1.0.0).
Updating sbt to 1.0.0 breaks compatibility with MMT, resulting in a bunch of "unresolved dependencies".

Downgrading sbt back to 0.13.6 and re-cloning MMT is a way  to get things to work again. Re-setup might be enough, I havent testet that, though.
If possible, it should be avoided to upgade sbt in the first place, at least for the moment.

There has since been a hotfix release (1.0.1.) for sbt, but that hasn't reached the [arch repositories](https://www.archlinux.org/packages/community/any/sbt/) yet. It could be possible that that is all that was needed to fix the problem, but it might also require some changes on our end.

I will keep you posted here.

**Comment by tkw1536** [comment]
I have the same issue with sbt 1.0.1 on MacOS. 
@jbetzend  do you have a link for an upstream issue so we can try and fix this?

**Comment by jbetzend** [comment]
I'm not certain that this is even an upstream issue. If it doesn't work with sbt hotfix 1.0.1., that might be evidence that the problem is on our end instead.

Since the version bump was major, we might simply be the victims of a breaking change. Maybe we all can look over the config files and see if we find a problem.

**Comment by tkw1536** [comment]
It appears that the major issue is that `org.scala-sbt.plugins#sbt-onejar` does not support sbt 1.x. We have two alternatives for this:
* use [sbt-assembly](https://github.com/sbt/sbt-assembly) instead, which has similar functionality as is compatible with the newest sbt version. 
* wait until support for `sbt 1.x` is added. It appears that a [pull request](https://github.com/sbt/sbt-onejar/commit/a62033406c7224af6bedb1efe8f4eea8e1b996e2) was merged in October, I do not know if this version has been published, or if we can just just upgrade to it.

**Comment by tkw1536** [comment]
I have a (very experimental) version of `sbt 1.x` support running on the [sbt-1.0 branch](https://github.com/UniFormal/MMT/tree/sbt-1.0). I will do some more testing with this and will likely end up rebasing / amending it, but feel free to test already.
