### ISSUE TITLE
more expansions, please

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [UniFormal/MMT#236]
I wrote something of the structure 
```
A' : type ❘= f (A) ❙
B : type ❘= A' → C❙
b : B❙
g : ( f(A) → C ) → X❙
D : g (b)❙
```
which currently fails at the last line, as the type of b is not getting expanded enough. 
Would it be possible to have that?

**Comment by florian-rabe** [comment]
Expanding types may indeed have some limitations.

I'm not sure yet what the right way to do it is.

**Comment by Jazzpirate** [comment]
can't reproduce the minimal example
