### ISSUE TITLE
Possibility to assign includes to includes in structures

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [UniFormal/MMT#237]
For some theory T

```
theory T : base:?Logic = 
  include ?S❙
  ...❙
❚
```
it would be really neat to have a way of including the same includes when using a structure
```
theory T' : base:?Logic = 
  structure t : ?T =
  	include S = S❙
  	...❙
  ❚
❚
```
(instead of copying everything, as is currently happening)

**Comment by florian-rabe** [comment]
The obvious design is to assume the identity whenever an included theory is not mentioned in a structure.

But there were some subtle problems with that.

In general, the design should be rethought and possibly amended.

**Comment by Jazzpirate** [comment]
I think this is taken care of now :)
