### ISSUE TITLE
Running a .msl file from a bash script

### ISSUE THREAD

**Issue by vv20** [UniFormal/MMT#238]
Is there currently functionality to run an MMT script from a bash script (i.e. something along the lines of "$java -jar MMT.jar my_script.msl"), or can scripts only be run from an MMT shell? If there is no such functionality, could it be implemented?

**Comment by tkw1536** [comment]
```java -jar mmt.jar --file my_script.msl``` should work. 

You can see the full list of command line arguments with  [java -jar mmt.jar --help](https://github.com/UniFormal/MMT/blob/master/src/mmt-api/resources/help-text/help.txt) . Depending on exactly what the script does (e.g if it starts up the webserver), you might also want to have a look at the different [run modes](https://uniformal.github.io/doc/setup/running.html).
