### ISSUE TITLE
MathScheme rename combinator: AdditiveMagma 

### ISSUE THREAD

**Issue by yasminemmagdi** [UniFormal/MMT#243]
![additivemagma](https://user-images.githubusercontent.com/22238052/33569984-6a48951a-d8f9-11e7-958e-6d761aba162f.png)

The function AdditiveMagma is defined as "Magma RENAME {+ := *}". The expanded theory appears in the web browser as: 
```
theory AdditiveMagma 
  include Empty 
  constant + : U -> U -> U 
```
It does not have the definition of the carrier. 

 The file that has the library definitions can be found here: https://gl.mathhub.info/MMT/mathscheme/blob/master/source/MathScheme.mmt

**Comment by tkw1536** [comment]
This should be an issue at https://gl.mathhub.info/MMT/mathscheme/issues instead.

**Comment by Jazzpirate** [comment]
Ah, yes, here, + really should be named * now. This is definitely a problem in our implementation

**Comment by yasminemmagdi** [comment]
@Jazzpirate 
This is how AdditiveMagma is defined: 
```
theory Carrier abbrev Empty EXTEND { U := term } 
theory Magma abbrev Carrier EXTEND { * : U → U → U  }
theory AdditiveMagma abbrev Magma RENAME {+ := *}
```
Therefore, an expanded AdditiveMagma, is expected to have a type U and a binary operator +. In this case the renaming work (* in Magma is renamed to + in AdditiveMagma), but the carrier (U := term) is not included in the definition of AdditiveMagma.

**Comment by florian-rabe** [comment]
I'm closing this because it is superseded by the latest devel (which Yasmine is already using).
