### ISSUE TITLE
MathScheme Rename Combinator: DoublyPointed01 

### ISSUE THREAD

**Issue by yasminemmagdi** [UniFormal/MMT#244]
The theory DoublyPointed01 is defined as "DoublyPointed RENAME { 0 := e , 1 := e2 }". The expanded theory is: 
```
theory DoublyPointed01 
  include Carrier 
  include Empty 
  include Pointed2Carrier 
```
Here there are two problems 
a. the expanded theory has one point, while the original one has two points. 
b. Having the expanded theory as a list of includes does not help determine whether the renaming took place or not 
![doublypointed01](https://user-images.githubusercontent.com/22238052/33570104-c2caa26e-d8f9-11e7-8b69-74e87b5560fa.png)

The file that has the library definitions can be found here: https://gl.mathhub.info/MMT/mathscheme/blob/master/source/MathScheme.mmt

**Comment by tkw1536** [comment]
This should be an issue at https://gl.mathhub.info/MMT/mathscheme/issues instead.

**Comment by florian-rabe** [comment]
I'm closing this because it is superseded by the latest devel (which Yasmine is already using).
