### ISSUE TITLE
MathScheme rename combinator: Semirings

### ISSUE THREAD

**Issue by yasminemmagdi** [UniFormal/MMT#246]
The theory of Semirings includes the axiom of associativity defined twice, once for * and once for +. The one defined for + comes from the additiveCommutativeMonoid by doing a rename of * in commutative monoid into +. But the expanded additiveCommutativeMonoid looks like: 
theory additiveCommutativeMonoid
  include Unital 
  include LeftUnital 
  include PointedMagma 
  include Magma 
  include Carrier 
  include Empty 
  include PointedCarrier 
  include RightUnital 
  include Semigroup 
  include CommutativeMagma 
So there is no axiom for the associativity of +, or if the renaming is done it cannot be seen, because the expanded theory is just a list of includes. 

![additivecommutativemonoid](https://user-images.githubusercontent.com/22238052/33570621-63a9572e-d8fb-11e7-9902-5343dd992016.png)

The file that has the library definitions can be found here: https://gl.mathhub.info/MMT/mathscheme/blob/master/source/MathScheme.mmt

**Comment by florian-rabe** [comment]
I'm closing this because it is superseded by the latest devel (which Yasmine is already using).
