### ISSUE TITLE
Migrate (Large parts of) MMT/examples to Test/General

### ISSUE THREAD

**Issue by Jazzpirate** [UniFormal/MMT#251]

**Comment by florian-rabe** [comment]
I think I want to keep the MMT/examples repository as it is.

We can use Test/General for non-sensical theories that we only write for testing, and MMT/examples for meaningful examples that can help users get started.

However, MMT/examples should be built during testing.

**Comment by tkw1536** [comment]
@Jazzpirate can this be closed?
