### ISSUE TITLE
Migrate `sbt install` task into MMT shell extension

### ISSUE THREAD

**Issue by tkw1536** [UniFormal/MMT#257]
At the moment, installing the MMT jars is done via the `sbt install` task. This leads to code duplication, for example the `File` class is redefined for sbt in [https://github.com/UniFormal/MMT/blob/master/src/project/File.scala](https://github.com/UniFormal/MMT/blob/master/src/project/File.scala). 

This should not be the case, instead we should make the install task an MMT-internal `:install` (or similar) shell extension. This can then easily be delegated to by sbt.

**Comment by tkw1536** [comment]
@florian-rabe what are your thoughts on this?

**Comment by florian-rabe** [comment]
It's OK the way it is.
