### ISSUE TITLE
find a place for mmt.rnc

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#259]
A while back I made a RelaxNG schema for the MMT XML syntax, now I am giving up the laptop, and so we should find a place to commit this for MMT. I am not sure where this should go, but I think it will be useful in the future. I am attaching the file (renamed to `mmt.rnc.txt` so that github will swallow it)
[mmt.rnc.txt](https://github.com/UniFormal/MMT/files/1561962/mmt.rnc.txt)

**Comment by kohlhase** [comment]
A possible resting place is with the tests.

**Comment by florian-rabe** [comment]
Currently, the 'scripts' directory in the main MMT repo is the best resting place.

The folder currently contains only a folder 'script/travis'.
After adding the rnc file, we may want to rename the 'scripts' folder.

**Comment by kohlhase** [comment]
OK, making a pull request out of this
