### ISSUE TITLE
sun.misc.BASE64Decoder not available on Java 9

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#260]
I cloned uniformal/MMT (master branch), downloaded jdk 9.01, installed sbt 1.04 via homebrew, and then ran `sbt deploy` in the `src` repos as advised. That seems to download scala 2.12.4 
Then I am getting the errors:  

```
[error] /Users/kohlhase/vc/git/github.com/UniFormal/MMT/src/mmt-odk/src/info/kwarc/mmt/odk/OpenMath/OMCoding.scala:76:61: type BASE64Encoder is not a member of package sun.misc
[error]   def bytes2Hex(bytes : List[Byte]) : String = new sun.misc.BASE64Encoder().encode(bytes.toArray)
[error]                                                             ^
[error] /Users/kohlhase/vc/git/github.com/UniFormal/MMT/src/mmt-odk/src/info/kwarc/mmt/odk/OpenMath/OMCoding.scala:77:59: type BASE64Decoder is not a member of package sun.misc
[error]   def hex2Bytes(hex : String) : List[Byte] = new sun.misc.BASE64Decoder().decodeBuffer(hex).toList
[error]                                                           ^
```
 and later 
```
[error] (odk/compile:compileIncremental) Compilation failed
[error] Total time: 81 s, completed 15 Dec 2017, 12:53:50
```
This should not happen.

**Comment by Jazzpirate** [comment]
sun.misc. looks like some java library to me. Either it's a version conflict with your java version or there's an additional dependency involved that I don't know about.
@tkw1536 you wrot odk/OpenMath, do you know where sun.misc.BASE64Encoder comes from?

**Comment by tkw1536** [comment]
This appears to be JDK 9 only, and there should be an easy mitigation by switching classes. I will do two things:
1. Add testing with both JDK 8 and JDK 9 to travis
2. Check that I can easily switch implementations of `sun.misc.BASE64Encoder`

**Comment by florian-rabe** [comment]
I myself am still using JDK 7, sbt 0.13, scala 2.11.

You're probably using newer versions where we haven't sorted out all issues yet.

There's some other issue about upgrading sbt and scala. In that context, we should upgrading to a modern JDK, too.
I understand @tkw1536 is working on that.
I understand

**Comment by kohlhase** [comment]
I agree that we should test on various versions. In particular, the new ones are important, because that is what people have when they get new machines.

**Comment by tkw1536** [comment]
I have investigated the concrete problem that Michael has. I have found the following:
*  `sun.misc.BASE64Encoder` -- which is currently used -- is available for `Java <= 8`
* `java.util.Base64` -- a drop-in alternative -- is available in `Java >= 8`

Hence we can not support both `Java 7` and `Java 9` at the same time (unless we do some really funky hacking that would do a conditional import, which I am not sure exists and even if it it does if it is worth the effort). 

I would prefer migrating to `java.util.Base64`, which means that we would no longer be able to compile the `mmt-openmath` project on Java 7. 

@florian-rabe @kohlhase Comments?

**Comment by kohlhase** [comment]
I think a hack at that point (version-sniffing) is completely OK, in fact much better than dropping old versions of Java.

**Comment by kohlhase** [comment]
sorry, misclicked

**Comment by florian-rabe** [comment]
So far, we've not used Java 8-only features.
But Java 7 hasn't been supported for 2 years, so it should be OK for us to start requiring Java 8.

We should upgrade to latest versions of java, scala, and sbt in one go.
@tkw1536 Are you looking into that? If so, do you know how easy it is/when we can do it?

**Comment by neoxp** [comment]
**### SOLUTION TO ERROR SUN / MISC / BASECODER64 IN ECLISPE.**

**INSTRUCTIONS TO SOLVE THE PROBLEM ARE:**

1- INSTALL WINDOWS XP SP2 WITH JAVA 6.

2- DOWNLOAD ADT VERSION 23.0.2 WITH SDK 19.

3- DECOMPRESS THE ADT AND INSTALL IT ON YOUR COMPUTER.

4- OPEN THE ECLIPSE AS ADMINISTRATOR AND IMPORT THE ANDORID FILE.

5- IN THE FILE project.properties WRITE THIS -> target = android-19.

6- EXPORT YOUR PROJECT AND NO MORE THIS ERROR WILL APPEAR.

7- AND SO WE SOLVE THE ERROR CHECKED AND RUNNING.

8- 100% CHECKED BY ME.

**Comment by victorwss** [comment]
@neoxp 

> 1- INSTALL WINDOWS XP SP2 WITH JAVA 6.

That is really a very stupid way to "solve" the problem. And it do not solve the real issue that is to run that in Java >= 9.

Even a stupid answer like "downgrade to Java 8" would be better than your ridiculous solution.

**Comment by florian-rabe** [comment]
@victorwss 
It seems that comment was spam - I've removed it.

**Comment by neoxp** [comment]
Not is stupid intall Windows Xp is the solution fir you problem.

I do not problem un Java 9 is not important for resoved you problem.

I understand the remove the my comment.

It is my solution is a solved the problem.

**Comment by qwfys** [comment]
You can replace sun.misc.BASE64Decoder with java.util.Base64。
