### ISSUE TITLE
Support Java 9

### ISSUE THREAD

**Issue by tkw1536** [UniFormal/MMT#263]
We should support Java 9. As far as I can see so far, this hinges on: 
- [x] testing multiple Java Versions in Travis
- [x] basic support by Scala / sbt (fixed in #262)
- [x] `sun.misc.BASE64Decoder` not being available on Java 9 (#260)
- [x] `mmt-metamath` does not compile under Java 9 because of dependencies
- [ ] `concept-browser` does not compile under Java 9 because of dependencies
- [ ] `scala-parser-combinators` support for Java 9

**Comment by florian-rabe** [comment]
According to http://www.oracle.com/technetwork/java/eol-135779.html Java 9 does not have the same release status and support cycle as Java 8.
That means we shouldn't make Java 9 a requirement for MMT.

Instead, we should require Java 8 or higher.

That means everybody should make sure their code runs under Java 8 or higher.
In general, we should get rid of Java method calls and external dependencies that work only on some Java 8 or only on Java 9.

**Comment by tkw1536** [comment]
@florian-rabe  The only way this can be achieved (IMO) is by taking care of #3.

**Comment by tkw1536** [comment]
Also, you can have at the travis tests, these test java 7 - 9. In this case: https://travis-ci.org/UniFormal/MMT/jobs/338343546#L2380-L2525

**Comment by florian-rabe** [comment]
According to http://www.scala-lang.org/news/2.12.0/ Scala itself is planning Java 9 support only for Scala 2.13.
So we should not actually spend time on this for now.

I'll update the documentation that MMT requires Java 8.

**Comment by kohlhase** [comment]
We have #432 now.
