### ISSUE TITLE
mmt make pdflatex should use -synctex=1

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#265]
currently `mmt make pdflatex` uses `xelatex` to format sTeX files (this is good for chinese and other foreign languages). The invocation of `xelatex` in `MMT/src/mmt-stex/run-latexml.sh1`

```
 cat "$preamble" "${theory}.tex" "$postamble" \
  | xelatex -jobname ${theory} -interaction scrollmode
```
should be changed to 
```
 cat "$preamble" "${theory}.tex" "$postamble" \
  | xelatex -jobname ${theory} -interaction -synctex=1 scrollmode
``` 
so that we can sync from the generated tex

**Comment by Jazzpirate** [comment]
done
