### ISSUE TITLE
Get testing stuff sorted

### ISSUE THREAD

**Issue by Jazzpirate** [UniFormal/MMT#290]
From all I can tell:
- building in "sbt test" throws different errors than building in a normal mmt instance
- running "sbt test" locally throws different errors than on travis
- this whole thing isn't consistent, really

Currently, travis tests have 0 information.

**Comment by Jazzpirate** [comment]
this is caused by #252

**Comment by florian-rabe** [comment]
scala-bin was somewhat experimental.

One should probably look at it carefully before using at in test.

**Comment by tkw1536** [comment]
Tests have been fixed, apart from a few files that should typecheck are not type checking.
