### ISSUE TITLE
setup just quits

### ISSUE THREAD

**Issue by AiraComet** [UniFormal/MMT#292]
Running java -jar mmt.jar just quits without doing anything.
Problem occurred on Ubuntu 16.04 LTS with mmt version: 094bcccff514d0fad0080e3fa6bddf29c543e5f9

**Comment by tkw1536** [comment]
So far I have not been able to reproduce this -- not sure what went wrong here.

**Comment by florian-rabe** [comment]
This is probably due a bug that has already been fixed on devel.
