### ISSUE TITLE
Potential feature request: Definition expansion up to specified theory

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [UniFormal/MMT#295]
Hi,

to analyze mathematical expressions like `Δ f` , I would like to be able to expand them up to a specified degree. For instance, the Laplace operator Δ could be in a theory 
```
theory DifferentialOperators : base:?Logic = 
  include ?derivatives ❙
   laplace_operator : {domain : type, codomain : type } (domain → codomain) → (domain → codomain) ❘ # Δ 3 ❘ = [domain : type, codomain : type , u : domain → codomain] ∂ ( ∂ u ) ❙ // exemplary, only true for 1-D ❙
❚
```
where the derivative `∂` is defined in `?derivatives`. I would now like to know how many derivatives are in total being applied to some `f` in `[f] Δ f`. So if I'd give the information that things should be expanded "up to" the theory `?derivatives`, the derivatives as well as the meta theory and all the things that `?derivatives` includes would not need to be expanded.

So the questions are: is this a sensible idea? Is it implementable?

**Comment by florian-rabe** [comment]
The question which definitions to expand when is very difficult for all formal systems.

It is straightforward to write *Scala* code for restricted definition expansion: just adapt the standard expander in the Lookup class.

I don't think it's needed to write *MMT* syntax for it.
But that need will probably come up eventually (e.g., if we build a tactic language for an MMT theorem prover).
