### ISSUE TITLE
Subtyping

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [UniFormal/MMT#296]
Hi,

I just wrote the subtyped variable
```
  myType = ⟨ ℝ | ([z] ⊦ z ≐ 1.0 ∨ z ≐ 2.0) ⟩ ❙
  a : myType ❘ = 1.0 ❙
```
but get the error "-- terms have different shape, thus they cannot be equal", because during the course of evaluation we get the "-Judgment |- ℝ = myType", which of course cannot be true.

I feel like this should be working?

**Comment by Jazzpirate** [comment]
it should not work ;) Subtyping is highly experimental anyway, but in this case type checking would require proving the object-level proposition 1.0 \doteq 1.0 v 1.0 \doteq 2.0 without any kind of automated proving on that level.
