### ISSUE TITLE
Type Inference

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [UniFormal/MMT#297]
Hi,

this should be working, right?
```
theory testTypeInference : base:?Logic = 
  A : type ❙
  C = A ❙
  B : type ❙
  B_on_A : B <* C ❙
❚
```
In fact, it fails because the type of C cannot be inferred.

**Comment by florian-rabe** [comment]
This was due to an ill-advised optimization in the StructureChecker.

I've removed it now (on devel).
