### ISSUE TITLE
Fix compiler warnings in mmt

### ISSUE THREAD

**Issue by tkw1536** [UniFormal/MMT#3]
There are a lot of non-exhaustive match warnings, it would be great if they would disappear (Maybe we can throw an exception in case they occur). 
![screen shot 2015-04-29 at 14 57 35](https://cloud.githubusercontent.com/assets/2923242/7391287/23b67998-ee80-11e4-93bc-13af78acdc28.jpg)
The same thing holds true for deprecation warnings.

**Comment by florian-rabe** [comment]
This should be done, ideally together with upgrading to Scala 2.12 (and sbt 1).

Please don't add bad code everywhere just because Scala style guide recommends it (e.g., ":Unit =" for all procedures).

**Comment by florian-rabe** [comment]
In mmt-api, I've removed all non-exhaustive warning except some in outdated code that is never run (e.g., the moc package).
It's good to keep those warnings because they indicate actual cleanup that should be done at some point.

**Comment by florian-rabe** [comment]
If we want to get rid of the warnings for cosmetic reasons, can we annotate all affected functions in moc in such a way that warnings are ignored and the functions are deprecated.

**Comment by jbetzend** [comment]
> outdated code that is never run (e.g., the moc package)

Is there a good reason why this code is still around if it's outdated and never run?

**Comment by florian-rabe** [comment]
Eventually, we'll have to fix it. So it's good to have the first attempt around.

**Comment by tkw1536** [comment]
I have fixed a whole bunch of warnings. Now remaining are:
- 105 scala-deprecation warnings
- 99 MMT-caused pseudo-deprecation warnings
- 2 warnings related to case-sensitivity of the file system

**Comment by jbetzend** [comment]
`mmt-imps` is also warning-free as of commit efd8682ae0b672b4e6016eb2edb0577aa935cbec (down from 104 Warnings before).

**Comment by tkw1536** [comment]
I have fixed all the 105 scala-caused deprecation warnings.

**Comment by jbetzend** [comment]
Very good. Maybe we can tackle some of the MMT-pseudo-deprecation warnings in the near-ish future.
Is there any data on what makes up these warnings? How much of them is just `getAllContent`, for example?

**Comment by tkw1536** [comment]
ok, so I think this issue can be closed now since all deprecations have been fixed some time ago.
