### ISSUE TITLE
MMT just dying when parsing

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [UniFormal/MMT#303]
After updating, I am having trouble to build mmt files. See the screenshot for details. Could this be part of yesterday's rework on the structure checker in [issue 297](https://github.com/UniFormal/MMT/issues/297), @florian-rabe ?

![screenshot from 2018-02-07 15-22-23](https://user-images.githubusercontent.com/9729409/35921431-da18cde8-0c1a-11e8-94e3-7fe45604f87f.png)

if you want to try the same file, find it in the interview_stuff branch in MitM/smglom/calculus.

**Comment by florian-rabe** [comment]
I can't see what the problem is.

**Comment by freifrauvonbleifrei** [comment]
have a look at the console window: it just quits when checking the type of "interval", parsing does not finish.

**Comment by florian-rabe** [comment]
But the screenshot doesn't show the declaration that fails.

In any case, if something takes forever, it's almost always an issue with subtyping.

**Comment by freifrauvonbleifrei** [comment]
Ok, after removing old jars and re-"sbt install"ing, the jedit console output looks different: 
![screenshot from 2018-02-07 17-46-01](https://user-images.githubusercontent.com/9729409/35929120-07c6cfce-0c2f-11e8-972f-e77beaba186a.png)

while this is the stacktrace I get in the console that I started jedit from:

> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1: Exception in thread "AWT-EventQueue-1" 
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1: java.lang.NoClassDefFoundError: info/kwarc/mmt/api/Rule$class
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.mitm.rules.Binary.priority(Literals.scala:96)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.RuleSet.$anonfun$getOrdered$1(Rule.scala:91)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.RuleSet.$anonfun$getOrdered$1$adapted(Rule.scala:91)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at scala.math.Ordering$$anon$5.compare(Ordering.scala:122)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.util.TimSort.sort(TimSort.java:220)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.util.Arrays.sort(Arrays.java:1438)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at scala.collection.SeqLike.sorted(SeqLike.scala:652)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at scala.collection.SeqLike.sorted$(SeqLike.scala:640)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at scala.collection.AbstractSeq.sorted(Seq.scala:41)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at scala.collection.SeqLike.sortBy(SeqLike.scala:627)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at scala.collection.SeqLike.sortBy$(SeqLike.scala:627)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at scala.collection.AbstractSeq.sortBy(Seq.scala:41)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.RuleSet.getOrdered(Rule.scala:91)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.uom.UOMState.<init>(RuleBasedSimplifier.scala:19)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.uom.RuleBasedSimplifier.apply(RuleBasedSimplifier.scala:54)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.uom.Simplifier.apply(Simplifier.scala:40)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.Solver.simplify(Solver.scala:1412)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.Solver.substituteSolved(Solver.scala:1424)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.Solver.$anonfun$inferType$20(Solver.scala:985)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at scala.Option.map(Option.scala:146)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.Solver.inferType(Solver.scala:985)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.Solver.inferTypeAndThen(Solver.scala:751)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.lf.ShallowPolymorphism$.apply(ShallowPolymorphism.scala:13)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.Solver.checkInhabitable(Solver.scala:1091)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.Solver.$anonfun$check$4(Solver.scala:787)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.History.indented(Constraints.scala:79)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.Solver.$anonfun$logAndHistoryGroup$1(Solver.scala:385)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.Logger.logGroup(Log.scala:34)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.Logger.logGroup$(Log.scala:31)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.Solver.logGroup(Solver.scala:80)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.Solver.logAndHistoryGroup(Solver.scala:384)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.Solver.$anonfun$check$2(Solver.scala:780)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.Solver$JudgementStore$.getOrElseUpdate(Solver.scala:806)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.Solver.check(Solver.scala:777)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.Solver.info$kwarc$mmt$api$checking$Solver$$activateRepeatedly(Solver.scala:681)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.Solver.apply(Solver.scala:585)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.Solver.applyMain(Solver.scala:569)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.RuleBasedChecker.$anonfun$apply$7(RuleBasedChecker.scala:56)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.Logger.logGroup(Log.scala:34)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.Logger.logGroup$(Log.scala:31)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.RuleBasedChecker.logGroup(RuleBasedChecker.scala:17)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.RuleBasedChecker.apply(RuleBasedChecker.scala:56)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.MMTStructureChecker.checkInhabitable$1(MMTStructureChecker.scala:235)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.MMTStructureChecker.$anonfun$check$12(MMTStructureChecker.scala:243)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.MMTStructureChecker.$anonfun$check$12$adapted(MMTStructureChecker.scala:240)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at scala.Option.foreach(Option.scala:257)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.MMTStructureChecker.check(MMTStructureChecker.scala:240)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.MMTStructureChecker.applyElementBegin(MMTStructureChecker.scala:57)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.TwoStepInterpreter$$anon$1.onElement(Interpreter.scala:85)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.parser.KeywordBasedParser.seCont(StructureParser.scala:96)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.parser.KeywordBasedParser.addDeclaration$1(StructureParser.scala:481)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.parser.KeywordBasedParser.readInModuleAux(StructureParser.scala:646)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.parser.KeywordBasedParser.readInModule(StructureParser.scala:461)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.parser.KeywordBasedParser.$anonfun$readTheory$2(StructureParser.scala:725)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.Logger.logGroup(Log.scala:34)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.Logger.logGroup$(Log.scala:31)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.parser.Parser.logGroup(Parser.scala:224)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.parser.KeywordBasedParser.readTheory(StructureParser.scala:725)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.parser.KeywordBasedParser.readInDocument(StructureParser.scala:411)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.parser.KeywordBasedParser.$anonfun$apply$1(StructureParser.scala:179)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.Logger.logGroup(Log.scala:34)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.Logger.logGroup$(Log.scala:31)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.parser.Parser.logGroup(Parser.scala:224)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.parser.KeywordBasedParser.apply(StructureParser.scala:179)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.parser.KeywordBasedParser.apply(StructureParser.scala:169)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.TwoStepInterpreter.apply(Interpreter.scala:92)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.checking.Interpreter.importDocument(Interpreter.scala:43)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.archives.Importer.buildFile(Index.scala:39)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.archives.TraversingBuildTarget.runBuildTask(BuildTarget.scala:528)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.archives.TraversingBuildTarget.checkOrRunBuildTask(BuildTarget.scala:455)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.archives.TrivialBuildManager.$anonfun$addTasks$1(BuildQueue.scala:181)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at scala.collection.immutable.List.foreach(List.scala:389)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.archives.TrivialBuildManager.addTasks(BuildQueue.scala:180)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.archives.TraversingBuildTarget.build(BuildTarget.scala:376)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.archives.TraversingBuildTarget.build(BuildTarget.scala:370)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.archives.BuildTarget.apply(BuildTarget.scala:216)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.actions.ArchiveActionHandling.$anonfun$buildArchive$1(ArchiveAction.scala:103)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.actions.ArchiveActionHandling.$anonfun$buildArchive$1$adapted(ArchiveAction.scala:80)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at scala.collection.immutable.List.foreach(List.scala:389)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.actions.ArchiveActionHandling.buildArchive(ArchiveAction.scala:80)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.actions.ArchiveActionHandling.buildArchive$(ArchiveAction.scala:79)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.Controller.buildArchive(Controller.scala:68)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.actions.ArchiveBuild.apply(ArchiveAction.scala:13)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.actions.ActionHandling.handle(ActionHandling.scala:53)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.actions.ActionHandling.handle$(ActionHandling.scala:41)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.Controller.handle(Controller.scala:68)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.actions.ActionHandling.handleLine(ActionHandling.scala:37)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.actions.ActionHandling.handleLine$(ActionHandling.scala:35)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.api.frontend.Controller.handleLine(Controller.scala:68)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at info.kwarc.mmt.jedit.MMTConsole.execute(MMTConsole.scala:37)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at console.Console.run(Console.java:605)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at console.Console.access$1300(Console.java:77)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at console.Console$RunActionHandler.actionPerformed(Console.java:1193)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at console.ConsolePane.fireActionEvent(ConsolePane.java:195)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at console.ConsolePane$EnterAction.actionPerformed(ConsolePane.java:447)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at console.ConsolePane.processKeyEvent(ConsolePane.java:346)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.Component.processEvent(Component.java:6310)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.Container.processEvent(Container.java:2236)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.Component.dispatchEventImpl(Component.java:4889)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.Container.dispatchEventImpl(Container.java:2294)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.Component.dispatchEvent(Component.java:4711)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.Component.dispatchEventImpl(Component.java:4760)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.Container.dispatchEventImpl(Container.java:2294)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.Component.dispatchEvent(Component.java:4711)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.EventQueue.access$500(EventQueue.java:97)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.EventQueue$3.run(EventQueue.java:709)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.EventQueue$3.run(EventQueue.java:703)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.security.AccessController.doPrivileged(Native Method)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.EventQueue$4.run(EventQueue.java:731)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.EventQueue$4.run(EventQueue.java:729)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.security.AccessController.doPrivileged(Native Method)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:700)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 5:45:13 PM [AWT-EventQueue-1] [error] AWT-EventQueue-1:  at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
>

**Comment by Jazzpirate** [comment]
the log output doesn't matter, it's just different because I changed what it logged when you showed me earlier, but what happens when you click the sidekick-parse-button isn't logged there anyway.

Then main thing is: the issue hasn't changes apparently

**Comment by florian-rabe** [comment]
Missing classes is most likely a 2.11 vs. 2.12.
Have you purged all old class files from archives and rebuild them 2.12?

**Comment by freifrauvonbleifrei** [comment]
is this something that i (being a user) am supposed to do? or is the question for the developers?

**Comment by Jazzpirate** [comment]
@florian-rabe the problem is that clicking the sidekick-parse-button doesn't seem to produce any result. It doesn't seem to run into an infinite loop, from experience I know that the latter usually blocks jedit/sidekick.

**Comment by Jazzpirate** [comment]
it does do something though, it shows the log output in the status bar of jedit at the bottom, but only single lines, which isn't helpful. The first screenshot shows what happens when you build the mmt file from the shell: it stops after the type of "interval", but doesn't even show the "no definiens"-line before it just stops.

**Comment by Jazzpirate** [comment]
@freifrauvonbleifrei can you confirm that the same happens with other files? in particular ones which should parse without problems (e.g. file in MitM/Foundation?)

**Comment by freifrauvonbleifrei** [comment]
yup, same situation there: 
![screenshot from 2018-02-07 18-03-41](https://user-images.githubusercontent.com/9729409/35930104-59b2da6a-0c31-11e8-8d9c-85ed2b7b5e92.png)

(tell me what to type if you like more concise console output :) )

**Comment by Jazzpirate** [comment]
ah! I can reproduce it on my machine

**Comment by Jazzpirate** [comment]
will investigate

**Comment by Jazzpirate** [comment]
Problem solved. The issue were leftover binaries in MitM/Foundation and MMT/urtheories. I rebuilt them and pushed; can you pull them and restart jedit?

**Comment by freifrauvonbleifrei** [comment]
yes, works again now. thanks!
