### ISSUE TITLE
Transitive Views?

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [UniFormal/MMT#304]
Hi,
let's assume I wrote something of the sort
```
theory A : base:?Logic = 
  A : type ❙
❚

theory B : base:?Logic = 
  B : type ❙
❚

view BasA : ?A → ?B = 
	A = B ❙
❚

theory C : base:?Logic = 
  C : type ❙
❚

view CasB : ?B → ?C = 
	B = C ❙
❚
```
And now I would like to establish a view from A to C using the info already there, for example:
```
view test_transitive_view : ?A → ?C = 
	include ?A = ?BasA ❙
	include ?B = ?CasB ❙
❚
```
which of course doesn't work, because there is no theory ?A or ?B included in `?A`. 

Is this concept already realizable in MMT somehow?

**Comment by florian-rabe** [comment]
This is just composition of morphisms.

MMT supports it, but I'm not sure if the concrete syntax does.
