### ISSUE TITLE
"community" tab links to "development"

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#315]
title says it. I would have expected a page that talks about who is developing and using MMT and for what. And how to get into contact; something more like https://uniformal.github.io/doc/development/contributors but also about mailing lists, etc. 

And we we should of course have a "development tag" in the web site.

**Comment by tkw1536** [comment]
The "Community" link now links to a new page https://uniformal.github.io/doc/community.html. 
I have also added a new "Development" link, that links to the same section as before. 

@florian-rabe Can you update the community page as you see fit and then close the issue?

**Comment by tkw1536** [comment]
closing, as there is nothing left to be done
