### ISSUE TITLE
tgview backend does not return anything

### ISSUE THREAD

**Issue by tkw1536** [UniFormal/MMT#342]
The extension appears to be loaded, but e.g. https://mmt.mathhub.info/:jgraph/json?key=thgraph&uri=ODK/ODK contains no content.

**Comment by Jazzpirate** [comment]
That's because it shound't. thgraph takes a theory as argument; not an archive. This does: https://mmt.mathhub.info/:jgraph/json?key=archivegraph&uri=ODK/ODK
