### ISSUE TITLE
Broken build: "More statistics" (Colin Rothgang)

### ISSUE THREAD

**Issue by makarius** [UniFormal/MMT#355]
Trying to push my own changes, I've come across a build problem with the current head version: f950841a87969b6a78da53f.

Maybe I've got something wrong or my side, or maybe there is really something broken here.

[error] /home/makarius/isabelle/MMT/repos/src/mmt-api/src/main/info/kwarc/mmt/api/ontology/ABox.scala:18:23: object lf is not a member of package info.kwarc.mmt
[error] import info.kwarc.mmt.lf._
[error]                       ^
[error] /home/makarius/isabelle/MMT/repos/src/mmt-api/src/main/info/kwarc/mmt/api/ontology/ABox.scala:169:22: not found: value Univ
[error]            case Some(Univ(1)) => (TypeConstructor(), p)
[error]                      ^
[error] /home/makarius/isabelle/MMT/repos/src/mmt-api/src/main/info/kwarc/mmt/api/ontology/ABox.scala:170:22: not found: value Univ
[error]            case Some(Univ(2)) => (Kind(), p)
[error]                      ^
[error] /home/makarius/isabelle/MMT/repos/src/mmt-api/src/main/info/kwarc/mmt/api/ontology/ABox.scala:171:22: not found: value Univ
[error]            case Some(Univ(n)) if n > 2 => (HighUniverse(), p) 
[error]                      ^
[error] four errors found
[error] (api / Compile / compileIncremental) Compilation failed
[error] Total time: 9 s, completed Jun 18, 2018 11:40:25 AM

**Comment by Jazzpirate** [comment]
[error] /home/makarius/isabelle/MMT/repos/src/mmt-api/src/main/info/kwarc/mmt/api/ontology/ABox.scala:18:23: object lf is not a member of package info.kwarc.mmt
[error] import info.kwarc.mmt.lf._
[error] ^

Yes, mmt-api really should not have access to lf - the former is the core api of MMT while the latter is an somewhat-optional add on; correspondingly the former should never depend on the latter.
@ColinRothgang this will not work, unfortunately. Can you refactor your code?

**Comment by ColinRothgang** [comment]
I'm not sure. I used the Univ(n) from mmt-lf (and only those), to
distinguish terms from type declarations (not sure whether there is anz
other way). I will remove this distinction for now.

**Comment by florian-rabe** [comment]
@ColinRothgang The idea was very good.

But MMT very strictly enforces foundation-independence: mmt-lf symbols may never be mentioned in the mmt-api code.

That's annoying in the short term because it forces us to carve out extension interfaces all the time.
But it's very in the long term because those extension interfaces make for very good code.

Have a look at the RelationalExtractor (or similar) interface.
I think the LF plugin can already use it to insert LF-specific relations into the rel files.

**Comment by ColinRothgang** [comment]
Pushed a fix. It should compile now.

**Comment by makarius** [comment]
OK, works again.
