### ISSUE TITLE
Expose safeSimplifyUntil to CheckingCallback

### ISSUE THREAD

**Issue by Jazzpirate** [UniFormal/MMT#362]
Several of the LFX computation rules require that either a subterm has a specific form (which can be dealt with using the new Simplifiability-return types), or more importantly, that an inferred type has a specific structural form (e.g. "type needs to be a Pi"). Since computation rules only have a CheckingCallback instead of a Solver, there's little one can do than to call CheckingCallback.simplify on the term and hope it results in a Pi, which is probably inefficient. Exposing safeSimplifyUntil to a CheckingCallback could lead to less simplification steps in those instances.

**Comment by florian-rabe** [comment]
Probably OK to add it to CheckingCallback.
