### ISSUE TITLE
Relational information is written only to content and MMT URIs for content and narration disagree

### ISSUE THREAD

**Issue by ColinRothgang** [UniFormal/MMT#365]
1. For some reason the additional relational information is written only to content by typedRelationalExtractor (via the relational manager, alongside with the data from the MMTExtractor).
2. For some other reason the statistics exporter only traverses over narration when writing (but gets the relational data from both content and narration from memory).
3. The MMT URIs written to the rel files by MMTExtractor disagree for the outputs to content vs. narration (for instance cds.omdoc.org vs. docs.omdoc.org or capitalization).

Hence, the statistic exporter never reads the information written to the rel files by the typedRelationalExtractor. Fixing any of the three issues should fix the problem.

The way I see it, neither 1, 2 nor 3 should be the case and all three issues are not specific to the StatisticsExporter.

**Comment by florian-rabe** [comment]
I don't understand. We should skype about it, but I don't have much time until the weekend.

**Comment by ColinRothgang** [comment]
I retract the issue, I think I understand what happens now:

1. That's by design, as the additional informations typically appear in theories.
2. Since, the exporter only exports documents and not theories
3. They document different things, this is also by design. 

This still doesn't explain why the data from the typedRelationalExtractor is not used, but narrows down the possibilities.
