### ISSUE TITLE
Cannot prove omitted_type

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [UniFormal/MMT#373]
Hi, 

when refactoring the MoSIS kernel to keep up with current changes in mmt (devel branch), I ran across something that used to work™ and now doesn't. 

I try to add a constant `f = [ x : ℝ] 100 ⋅ sin(x)` to a theory `f` (which includes the necessary symbols, e.g. from MitM/Foundation?Math). What I get is the following: 

> invalid unit: http://mathhub.info/MitM/smglom/calculus/differentialequations?f?f?definition: Judgment  |- [x:ℝ]100⋅(sin x) : /omitted_type. 

is this intentional?

stacktrace:
> <div xmlns="http://www.w3.org/1999/xhtml">
>   <div>
>     <div class="error">
>       <div><span class="name">info.kwarc.mmt.api.InvalidUnit</span> of level <span class="level">2</span></div>
>       <div class="message">invalid unit: http://mathhub.info/MitM/smglom/calculus/differentialequations?f?f?definition: Judgment  |- [x:ℝ]100&#8901;(sin x) : /omitted_type</div>
>       <div class="stacktrace">
>         <div class="stacktraceline">
>           <span>info.kwarc.mmt.api.checking.RuleBasedChecker.$anonfun$apply$15(RuleBasedChecker.scala:97)</span>
>         </div>
>         <div class="stacktraceline">
>           <span>info.kwarc.mmt.api.checking.RuleBasedChecker.$anonfun$apply$15$adapted(RuleBasedChecker.scala:96)</span>
>         </div>
>         <div class="stacktraceline">
>           <span>scala.collection.immutable.List.foreach(List.scala:389)</span>
>         </div>
>         <div class="stacktraceline">
>           <span>info.kwarc.mmt.api.checking.RuleBasedChecker.$anonfun$apply$14(RuleBasedChecker.scala:96)</span>
>         </div>
>         <div class="stacktraceline">
>           <span>scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)</span>
>         </div>
>         <div class="stacktraceline">
>           <span>info.kwarc.mmt.api.frontend.Logger.logGroup(Log.scala:34)</span>
>         </div>
>         <div class="stacktraceline">
>           <span>info.kwarc.mmt.api.frontend.Logger.logGroup$(Log.scala:31)</span>
>         </div>
>         <div class="stacktraceline">
>           <span>info.kwarc.mmt.api.checking.RuleBasedChecker.logGroup(RuleBasedChecker.scala:17)</span>
>         </div>
>         <div class="stacktraceline">
>           <span>info.kwarc.mmt.api.checking.RuleBasedChecker.apply(RuleBasedChecker.scala:93)</span>
>         </div>
>         <div class="stacktraceline">
>           <span>info.kwarc.mmt.api.checking.MMTStructureChecker.$anonfun$check$16(MMTStructureChecker.scala:301)</span>
>         </div>
>         <div class="stacktraceline">
>           <span>info.kwarc.mmt.api.checking.MMTStructureChecker.$anonfun$check$16$adapted(MMTStructureChecker.scala:277)</span>
>         </div>
>         <div class="stacktraceline">
>           <span>scala.Option.foreach(Option.scala:257)</span>
>         </div>
>         <div class="stacktraceline">
>           <span>info.kwarc.mmt.api.checking.MMTStructureChecker.check(MMTStructureChecker.scala:277)</span>
>         </div>
>         <div class="stacktraceline">
>           <span>info.kwarc.mmt.api.checking.MMTStructureChecker.applyElementBegin(MMTStructureChecker.scala:72)</span>
>         </div>
>         <div class="stacktraceline">
>           <span>info.kwarc.mmt.interviews.InterviewServer$$anon$1.onElement(InterviewServer.scala:94)</span>
>         </div>
>         <div class="stacktraceline">
>           <span>info.kwarc.mmt.api.parser.KeywordBasedParser.seCont(StructureParser.scala:99)</span>
>         </div>
>         <div class="stacktraceline">
>           <span>info.kwarc.mmt.api.parser.KeywordBasedParser.addDeclaration$1(StructureParser.scala:484)</span>
>         </div>
[some more kilometers of stacktrace]

**Comment by Jazzpirate** [comment]
The stacktrace isn't really helpful - the proof tree might be. Have you tried explicitly giving the type ℝ->ℝ?

**Comment by freifrauvonbleifrei** [comment]
Giving the type returns the same: 

> invalid unit: http://mathhub.info/MitM/smglom/calculus/differentialequations?f?f?definition: Judgment  |- [x:ℝ]100⋅(sin x) : ℝ⟶ℝ

It does work e.g. for `f = [ x : ℝ] x ⋅ x` , `f = [ x : ℝ] sin(x)`, `f = [ x : ℝ] x ⋅ sin(x)`  and `f = [ x : ℝ] 100` though.

**Comment by Jazzpirate** [comment]
can you give me the proof tree? (in jEdit, by expanding the error message, in the shell by logging object-checker)

**Comment by freifrauvonbleifrei** [comment]
and `f = [ x : ℝ] 100 ⋅ x` fails as well.

**Comment by Jazzpirate** [comment]
oh, wait, nevermind, it's because it infers the type of multiplication from the first argument. Try "100.0" instead

**Comment by freifrauvonbleifrei** [comment]
grml, but that used to work, really!

**Comment by Jazzpirate** [comment]
I believe you. No idea why though :D
