### ISSUE TITLE
Subtyping notation

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [UniFormal/MMT#374]
Hi,

parsing the following theory
```
theory Domain : base:?Logic = 
  domain : type ❙
  boundary : type ❙
  boundary_on_domain : boundary <* domain ❙
❚
``` 
gives me errors of the type 

> 14:unbound token: <
> 14:unbound token: *
> 14:invalid unit: http://mathhub.info/MitM/smglom/calculus/differentialequations?mDomain?boundary_on_domain?type: Judgment  |- boundary < * domain INHABITABLE: boundary < * domain

did something change in the notation?

**Comment by Jazzpirate** [comment]
Subtyping has been moved to a different theory "base:?Subtyping"

**Comment by freifrauvonbleifrei** [comment]
thx! unfortunately, it opened up another issue...
