### ISSUE TITLE
Subtype handling

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [UniFormal/MMT#375]
once I used to be able to use subtyping like this, i.e. that mmt would notice `boundary` being a subtype of `domain`

```
theory example : base:?Logic = 	
	include base:?Subtyping ❙
  domain : type ❙
  boundary : type ❙
  boundary_on_domain : boundary <* domain ❙
  ucodomain : type ❙
	
  BC : {where: boundary} (domain ⟶ ucodomain) ⟶ ucodomain ❘ = [where, rhs] [u] u where ❙
❚
```
but now:

336:invalid unit: http://mathhub.info/MitM/smglom/calculus/differentialequations?example?BC?definition: Judgment  |- [where,rhs][u](u where)≐rhs : {where:boundary,rhs:ucodomain}(domain⟶ucodomain)⟶prop: where

**Comment by Jazzpirate** [comment]
as always when things become non-obvious, I'd need a proof tree please ;)

**Comment by Jazzpirate** [comment]
do you have the odk plugin loaded?

**Comment by freifrauvonbleifrei** [comment]
![screenshot from 2018-07-23 11-10-12](https://user-images.githubusercontent.com/9729409/43067953-44f9c4e8-8e69-11e8-8ee0-5e3e54738f07.png)

**Comment by Jazzpirate** [comment]
> how/when would I load that plugin?
Everytime you restart jEdit/MMT, unless you give it an .msl file (in the Plugin options)
The easiest way to do that is to create a new .msl file and write in it:

> extension info.kwarc.mmt.odk.Plugin
Alternatively, you have to write that in the MMT shell every time you restart

**Comment by Jazzpirate** [comment]
@screenshot: There's things cut off at the right side, so I can't see the actual judgments it's trying to prove

**Comment by freifrauvonbleifrei** [comment]
k, I have loaded that plugin but don't see obvious differences: 
![screenshot from 2018-07-23 13-48-38](https://user-images.githubusercontent.com/9729409/43075060-b7aff03c-8e7f-11e8-93f8-9aa3954ad7ea.png)

**Comment by Jazzpirate** [comment]
okay, then let me try to decode this now:
`BC : {where: boundary} (domain ⟶ ucodomain) ⟶ ucodomain ❘ = [where, rhs] [u] u where ❙`

we have:
`where : boundary` and `rhs : domain: ucodomain` - what type should `u` have though? If your constant is well-typed, then `[u] u` would have to have type `ucodomain`, but the latter has type `type`...?

**Comment by freifrauvonbleifrei** [comment]
oh sorry, of course! the second lambda term was supposed to go when I simplified the example.
this is what the full thing was supposed to look like:
![screenshot from 2018-07-23 15-03-06](https://user-images.githubusercontent.com/9729409/43078193-0e047340-8e8a-11e8-8ae2-ba9fc0bb34a4.png)

And in fact it is resolved by loading the odk plugin.
