### ISSUE TITLE
Views on subtypes: "no assignment for subtypeJudge found"

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [UniFormal/MMT#384]
When I try to map subtyped variables in a view, something strange happens:
```
theory T : base:?Logic = 	
	include base:?Subtyping ❙
  domain : type ❙
  boundary : type ❙
  boundary_on_domain : boundary <* domain ❙
❚

theory A : base:?Logic = 	
	include base:?Subtyping ❙
  myDomain : type ❙
  myBoundary : type ❙
  myBoundary_on_myDomain : myBoundary <* myDomain ❙
❚

view AasT : ?T →  ?A =
	domain = myDomain ❙ 
	boundary = myBoundary ❙
	boundary_on_domain = myBoundary_on_myDomain ❙
❚
```

> 348:error while adding successfully parsed element http://mathhub.info/MitM/smglom/calculus/differentialequations?AasT?[http://mathhub.info/MitM/smglom/calculus/differentialequations?T]/boundary_on_domain: get error: no assignment for subtypeJudge found in http://mathhub.info/MitM/smglom/calculus/differentialequations?AasT (empty assignment)

Even though the ODK plugin is loaded this time ;)

**Comment by Jazzpirate** [comment]
> no assignment for subtypeJudge found

That's becasue the subtyping theory isn't included in the codomain of the view ;)

**Comment by Jazzpirate** [comment]
oh sorry; it is, but you have to map it explicitly then.

Try (in the view)

include base:?Subtyping = base:?Subtyping ;)

**Comment by freifrauvonbleifrei** [comment]
phew, I was not used to that any more ;)
