### ISSUE TITLE
Subtype relation between family of types

### ISSUE THREAD

**Issue by Student-A** [UniFormal/MMT#386]
I'm assuming this is a bug. Please let me know in case it's just missing implementation.

	theory Test = 
		include http://gl.mathhub.info/MMT/LFX/Subtyping?LFSubtyped ❙
		boundary: type ⟶ type ❙
		boundary_is_subtype: {g: type} boundary g <* g ❙
   
		geom: type ❙
		f: geom ⟶ type ❙
		bound: type ❘ = boundary geom ❙
   
		works: {x: geom} f x ❙
		should_work_since_bound_is_subtype_of_geom: {x:bound} f x ❙
	❚

[Screenshot of error message](https://i.imgur.com/ar2ESkt.png)

Writing "boundary_is_subtype: bound <* geom ❙" works as usual. But I'm looking to make it for each pair of (type,boundary) that I create.

**Comment by florian-rabe** [comment]
It looks like it could work - depending on the behavior of <*.

But that is experimental.
