### ISSUE TITLE
Infix notation does not work

### ISSUE THREAD

**Issue by makarius** [UniFormal/MMT#394]
This is for MMT/01e0736c15fd and Isabelle/d75cd481f8d9.

The included example shows that infix notation does not work, even though the HTML server shows that it is present in the declaration (see "Pure.eq" and "op"):

    theory Test imports Pure
    begin
    
    definition op :: "'a ⇒ 'a ⇒ 'a"  (infix "**" 60)
      where "x ** y ≡ x"
    
    end

![infix](https://user-images.githubusercontent.com/4053140/45918785-5543b680-be8c-11e8-97ee-199405d86338.png)

**Comment by makarius** [comment]
Same problem: on the screenshot you can see the declaration of Pure.imp with infix syntax, but the output at the bottom uses prefix.
![pure_infix](https://user-images.githubusercontent.com/4053140/45979584-cbdce180-c04f-11e8-83d4-9b9ea74c894c.png)

**Comment by florian-rabe** [comment]
It seems Pure lacks the include of urtheories?PLF.

If true, that would explain the behavior.

**Comment by makarius** [comment]
After many variations on meta theory vs. included theories, it still does not work (e.g. see c5e3cdf2c8a555d646cb446c10f2230d3403e21c).

**Comment by florian-rabe** [comment]
I can debug if I see the some examples of the generated files.

**Comment by makarius** [comment]
See now https://gl.mathhub.info/Isabelle/Distribution

**Comment by florian-rabe** [comment]
Uncurrying was not implemented completely during presentation.

You should still add a notation for Pure.all

**Comment by florian-rabe** [comment]
Also, can you change the notations from presentationDim to parsingDim?

presentationDim should only be used for 2-dimensional notations (subscripts, fractions, etc.).

**Comment by makarius** [comment]
OK, works. I've also made some improvements concerning prefix and binder notation.
