### ISSUE TITLE
Parser crashes with NullPointer on missing comma in Pi

### ISSUE THREAD

**Issue by jbetzend** [UniFormal/MMT#395]
I found a bug in the parser. While parsing a pi type, if you forget the comma between two arguments, the parser crashes unhelpfully with a NullpointerException.

Here's a minimal breaking example.

> theory NullPointerBugExample : http://cds.omdoc.org/urtheories?PLF =
>   breaks : {t1 : type t2 : type} type❙
>❚

This should probably give a meaningful error message instead of just crashing with nullpointer.

**Comment by florian-rabe** [comment]
Do you have the stracktrace?

**Comment by jbetzend** [comment]
Not a helpful one...

![stacktrace](https://user-images.githubusercontent.com/1606110/45974293-405c5400-c041-11e8-8d72-c03b27180841.png)

**Comment by florian-rabe** [comment]
There should be more stacktrace underneath.

MMT keeps track of the original cause when catching and rethrowing an exception.
MMT's stacktrace includes the Java stacktraces of all of these. Usually, the last one (i.e., the original error) is the most helpful.

**Comment by jbetzend** [comment]
> There should be more stacktrace underneath.

There isn't, though. This is all jEdit gives me (MMT plugin was recently updated, too). I don't get any more stacktrace.

**Comment by florian-rabe** [comment]
Are you sure? Something the scrolling in jEdit ErrorList does not work correctly even though there are more lines.

**Comment by jbetzend** [comment]
ಠ_ಠ
![stacktrace2](https://user-images.githubusercontent.com/1606110/45974832-dba1f900-c042-11e8-9ac1-8423e6766bac.png)

**Comment by florian-rabe** [comment]
The full error message is longer and should be shown.

Anyway, you can always get more informative error messages by calling MMT from the MMT shell (usually called from within your IDE).
I've done that, where the whole error message is shown, and fixed the bug.
