### ISSUE TITLE
Proper SourceRef location and URL (not file:///)

### ISSUE THREAD

**Issue by makarius** [UniFormal/MMT#396]
This is for MMT/01e0736c15fd and Isabelle/d75cd481f8d9.

The Isabelle importer writes formal theory sources into directory `source` within the target archive. The SourceRef derived from that is a physical file URL, e.g. `file:///home/makarius/isabelle/MMT/isabelle_mmt/source/FOL/FOL/FOL.theory#375.19.2:383.19.10`

What is the proper way to produce a symbolic URL?

Is that the correct place for generated sources, or should they go into `content` (or something else)?

**Comment by florian-rabe** [comment]
The URIs in the source references should be of the form
  a.narrationBase / source/FOL/FOL/FOL.theory#375.19.2:383.19.10
where a is the archive.
