### ISSUE TITLE
Problem with mmt_type_checking

### ISSUE THREAD

**Issue by makarius** [UniFormal/MMT#399]
This is MMT/f002e1f2e2e6 and Isabelle/6e1b569ccce1.

The option `mmt_type_checking` already works for some basic examples, e.g. `$ISABELLE_HOME/src/HOL/Isar_Examples/First_Order_Logic.thy`

There are remaining problems with the representation of type classes and sort constraints, e.g. see the included files.
[Test.thy.txt](https://github.com/UniFormal/MMT/files/2424221/Test.thy.txt)
[$Test.$Test.omdoc.txt](https://github.com/UniFormal/MMT/files/2424231/Test.Test.omdoc.txt)

The error is produced as follows:
$ isabelle mmt_import -o mmt_archive_narration_base="https://isabelle.in.tum.de" -o mmt_type_checking=true -D ~/tmp/Test

      *** FAILED theory Test.Test
      *** Failed to check term: (http://cds.omdoc.org/urtheories?LambdaPi?Pi ['a : http://cds.omdoc.org/urtheories?Typed?type] (http://cds.omdoc.org/urtheories?LambdaPi?arrow (http://cds.omdoc.org/urtheories?LambdaPi?apply https://isabelle.in.tum.de?Test.Test?Test.Test,class,Test.c 'a) (http://cds.omdoc.org/urtheories?LambdaPi?Pi [x : 'a] (http://cds.omdoc.org/urtheories?LambdaPi?apply (http://cds.omdoc.org/urtheories?LambdaPi?apply https://isabelle.in.tum.de?Test.Test?Test.Test,const,Test.d 'a) x))))
      *** inferred: {'a:type}Test.Test,class,Test.c 'a⟶{x:'a}(Test.Test,const,Test.d 'a) x : Pure,type,prop
      ***  inferred: Test.Test,class,Test.c 'a⟶{x:'a}(Test.Test,const,Test.d 'a) x : Pure,type,prop
      *** - inferred: {x:'a}(Test.Test,const,Test.d 'a) x : Pure,type,prop
      *** -- inferred: (Test.Test,const,Test.d 'a) x : Pure,type,prop
      *** --- no arguments, type is: Pure,type,prop
      *** --- substituting argument in return type
      *** --- argument is: x
      *** --- function type is: 'a⟶Pure,type,prop
      *** --- substituting argument in return type
      *** --- argument is: 'a
      *** --- function type is: {'a:type}'a⟶Pure,type,prop
      *** --- inferring type of function Test.Test,const,Test.d
      *** --- applying inference rule rule ApplyTerm for apply
      *** --- applying inference rule rule PolymorphicApplyTerm for apply
      *** -- inferring type of (Test.Test,const,Test.d 'a) x
      *** -- Judgment include ?Test.Test, 'a:type, _:Test.Test,class,Test.c 'a |- type : kind
      *** -- applying inference rule rule PiTerm for Pi
      *** - inferring type of {x:'a}(Test.Test,const,Test.d 'a) x
      *** ---- terms have different shape
      *** ---- both terms are stable
      *** ----  no applicable type-based rule, trying term-based equality
      *** --- Judgment include ?Test.Test, 'a:type |- type = kind
      *** --- no applicable subtyping rules, falling back to checking equality
      *** --- not obviously equal, trying subtyping
      *** -- Judgment include ?Test.Test, 'a:type |- type <: kind
      *** - Judgment include ?Test.Test, 'a:type |- Pure,type,prop : kind
      *** - applying inference rule rule PiTerm for Pi
      ***  inferring type of Test.Test,class,Test.c 'a⟶{x:'a}(Test.Test,const,Test.d 'a) x
      ***  Judgment include ?Test.Test |- kind : kind
      ***  applying inference rule rule PiTerm for Pi
      *** inferring type of {'a:type}Test.Test,class,Test.c 'a⟶{x:'a}(Test.Test,const,Test.d 'a) x
      *** Judgment include ?Test.Test |- {'a:type}Test.Test,class,Test.c 'a⟶{x:'a}(Test.Test,const,Test.d 'a) x : expected_type
      *** in declaration of fact "Test.bad"

**Comment by florian-rabe** [comment]
Test.c 'a must be a type.
