### ISSUE TITLE
MathWebSearch integartion

### ISSUE THREAD

**Issue by florian-rabe** [UniFormal/MMT#401]
@kohlhase @tkw1536 

We need a search interface backed by MathWebSearch.

The backend already exists in MMT (build target for harvest generation, abstraction around mws service).
This has already worked in MMT's own browser.

Missing are
* frontend (search bar, result display etc.)
* actually running MathWebSearch

**Comment by tkw1536** [comment]
closing, moved to MathHub issue tracker https://github.com/MathHubInfo/Frontend/issues/42
