### ISSUE TITLE
Source references to gitlab in MathHub

### ISSUE THREAD

**Issue by florian-rabe** [UniFormal/MMT#402]
@kohlhase @tkw1536 

When viewing sources in gitlab, every line has an id attribute.

So we can add links to the sources files to all MMT elements that have source references.
We should do that.

**Comment by kohlhase** [comment]
Indeed, this is very good to know. I think this should be integrated into some kind JOBAD-like functionality. 
The IDs are of the form 
```
https://gl.mathhub.info/ODK/ODK/blob/master/build.msl#L9
```
So we only need to export the sourcerefs we have which have a file and line number component (start line number) through the presentation process. 
Then we can pick up the source references via JS.

**Comment by tkw1536** [comment]
closing, moved to the MathHub issue tracker https://github.com/MathHubInfo/Frontend/issues/41
