### ISSUE TITLE
MMT surface syntax highlighting in rougue.

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#410]
We would like to have MMT surface syntax highlighting for MathHub (see https://github.com/MathHubInfo/Frontend/issues/49). It seems that GitLab uses [rouge](http://rouge.jneen.net/), so it would be very good to have an implementation of that.

Assigning to Florian and Dennis, maybe they have an idea who could do this.

**Comment by florian-rabe** [comment]
I recall they use two different frameworks - one for display and one for editing.
In the latter case, they use codemirror and pygments.
My information may be outdated though.

If the MathHub maintainers set up a hello-world self-documenting highlighting file and point us to it, Dennis or I could edit it with the actual grammar.

I would store the syntax highlighting files in the MMT/scripts directory as they might be reusable in other applications.
MathHub would need to pull them from there.

**Comment by ComFreek** [comment]
I created a Pygments lexer:

![image](https://user-images.githubusercontent.com/1827709/59698193-7523c300-91ef-11e9-8c4b-80ec2d3e4a40.png)

Code is so far at https://gist.github.com/ComFreek/cea196902d96323734c0162c5cb8c81a. I think this repo is a good place, although we should it put it on Pip as well. (Or instead maybe we can contribute it to Pygment's official list of supported languages directly?)

Not sure about usage on the web, maybe by prelexing on the server side (?). With LaTeX it can be used as follows:
```
% You MUST USE XeLaTeX (or other LaTeX-derivatives which support Unicode)
\usepackage{fontspec}

% Download GNU Unifont from http://unifoundry.com/unifont/index.html
% And save it, say, as "fonts/unifont-12.1.02.ttf"
\newfontfamily\unifont{unifont-12.1.02.ttf}[Path=./fonts/,NFSSFamily=unifont]

% Disable caching for debugging purposes (increases compilation times!)
\usepackage[cache=false]{minted}
\setminted{
	fontfamily=unifont
}

\begin{document}
	% mmt-lexer.py is my lexer file
	\inputminted{mmt-lexer.py:MMTLexer -x}{your-mmt-file.mmt}
\end{document}
```

**Comment by ComFreek** [comment]
I created an exporter from my Pygments lexer to a Rouge one. That being incorporated into the official Rouge library (and then into GitLab) is being discussed at https://github.com/rouge-ruby/rouge/pull/1585.
Closing this.
