### ISSUE TITLE
Errors from XML Streaming

### ISSUE THREAD

**Issue by jbetzend** [UniFormal/MMT#416]
The current devel-version of MMT has some problems with XML parsing, somehow related to documents, it appears. When I run my IMPSTest class, it crashes mid-translation (relatively early, during the second theory or so).

Here's the probably most relevant part of the stacktrace:

`error: streamer: error while parsing XML`
`...`
`debug: caused by`
`debug: class java.util.NoSuchElementException: null`
`debug: scala.collection.LinearSeqOptimized.last(LinearSeqOptimized.scala:146)`
`debug: scala.collection.LinearSeqOptimized.last$(LinearSeqOptimized.scala:145)`
`debug: scala.collection.immutable.List.last(List.scala:86)`
`debug: info.kwarc.mmt.api.documents.Document.<init>(Document.scala:29)`
`debug: info.kwarc.mmt.api.backend.XMLReader.readDocument(ReadXML.scala:62)`

Here's the full stacktrace: [streamer_xml_errors.txt](https://github.com/UniFormal/MMT/files/2652940/streamer_xml_errors.txt)

@florian-rabe, any ideas on this?

**Comment by florian-rabe** [comment]
Could have been introduced by my recent commit.
But I don't see how.

Can you set a breakpoint at Document.scala:29 and check if all variables have the right values?

The stacktrace indicates that path.name (on which .last is called) is null, but I can't see how that's possible.

**Comment by florian-rabe** [comment]
Try again. I fixed a bug that may have been related.

**Comment by jbetzend** [comment]
Yes, it seems to not be a problem anymore. Thank you.
