### ISSUE TITLE
*pdf* build targets should not trigger the tikzsvg target

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#464]
Currently the `pdflatex` build target triggers the `tikzsvg` target, but `pdflatex` does not need the svg. The OMDoc format generated by the `latexml` target does. So we should remove that dependency. All other targets (e.g. `allpdf` should get fixed as well). 
I guess that now this is easy for @jbetzend to do.

**Comment by kohlhase** [comment]
I will help, this would also speed up the build of large files like the various course notes.

**Comment by kohlhase** [comment]
Also, we should look closely at the dependencies of tikzsvg. It seems that they are never up to date and thus are always built.

**Comment by jbetzend** [comment]
Closed as of commit bd7fa95. MMT now forgets all tikzsvg dependencies unless running a latexml target (so this automatically fixes all targets, no need to do special things for `pdflatex` and `allpdf` and such).

As predicted, this cuts down build times of larger files _significantly_. I ran a quick test on the IWGS notes of this semester and got a reduction in build time of more than 93%, from just over a minute to less than five seconds. :smiley:
