### ISSUE TITLE
build pdflatex on exams incomplete

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#465]
I have tried it with the exam on  `MiKoCourses/AI/source/WS1819/exam.tex` and there are still missing sms files which are not generated automatically. 
We should look into this. I am suspecting that `\includemhproblem` is not recursing properly.

**Comment by kohlhase** [comment]
And while we are at it, we should probably look into `\includemhassignment`, which very likely has the same problem. That can be tested with `MiKoCourses/source/SS18/assignments.tex`

**Comment by jbetzend** [comment]
The former part, about `\includemhproblem` not recursing properly (it was exactly that) is fixed as of 99bd70e, I tested it successfully with the IWGS retake exam.

As for the latter, it seems `\includemhassignment` doesn't appear in the code as `\includemhproblem` and such do. And I can't find any use of it in either IWGS or AI.
Could you clarify where I can find usages of that (you seem to have accidentally omitted that from your post above) and what the semantics are there?

**Comment by kohlhase** [comment]
Sorry, you are right. There are `\includeassignment` and `\inputassignment`, which should behave exactly like `\includeproblem`. And there is `\includemhassignment` and `\inputmhassignment`, which should behave exactly like `\includemhproblem`.
You can test `\includeassignment` on `MiKoCourses/IWGS/source/WS1819/assignments.tex`.

**Comment by jbetzend** [comment]
Fixed as of commit 1027249, the assignments.tex now builds fine when it didn't build at all before.

`\includeassignment`, `\inputassignment`, and `\includeproblem` are treated _exactly_ the same, as are `\includemhassignment`, `\inputmhassignment`, and `\includemhproblem`
