### ISSUE TITLE
make tikzsvg generated content. 

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#466]
Currently, the `tikzsvg` build target builds the `*.svg` files as siblings of the corresponding `*.tex` files. This breaks the systematics that generated files should be in the `content` or `narrative` dimension of the archive. We should fix this in light of the "managed content" distribution (see https://github.com/MathHubInfo/MathHub/issues/5) regime we want to implement soon for MathHub. 
I suspect that the SVG files should go into the `content` dimension somewhere. We should discuss this with @tkw1536.

**Comment by jbetzend** [comment]
Fixed as of commit e4d5f11. 
The up-to-date-check for the generated images also works fine, #464 mentioned an issue with that.
