### ISSUE TITLE
external links in frames do not work properly

### ISSUE THREAD

**Issue by cmaeder** [UniFormal/MMT#47]
The external links to ANSI stuff in https://svn.kwarc.info/repos/MMT/doc/html/index.html#/applications/shell.html do not work or only if opened in another tab or window.

For some reason it works for a local copy and on http://kwarc.github.io/MMT/doc/html/index.html#applications/shell.html

**Comment by cmaeder** [comment]
The links above no longer show the shell.html page directly but got to  https://svn.kwarc.info/repos/MMT/doc/html/index.html where one has to click on `shell` under `applications` on the left hand side.
(click on `applications` to collapse or reopen the menu.)

**Comment by cmaeder** [comment]
A proper link to the shell is https://svn.kwarc.info/repos/MMT/doc/html/index.html#applications/shell.html (however, this URL does not change when navigating).

**Comment by cmaeder** [comment]
The problem seems to be `https` versus `http` see https://developer.mozilla.org/en-US/docs/Security/MixedContent. "Starting in Firefox 23, mixed active content is blocked by default" and my web console reports:

```
Blocked loading mixed active content "http://en.wikipedia.org/wiki/ANSI_escape_code
```

"To fix this error, requests to HTTP content should be removed and replaced with content served over HTTPS".

**Comment by cmaeder** [comment]
I could change the ANSI wikipedia page to use `https`, but this does not work for http://mihai-nita.net/2013/06/03/eclipse-plugin-ansi-in-console/.

For https://github.com/adoxa/ansicon a blank page is displayed within the frame (indicating a frame killer).

**Comment by kohlhase** [comment]
this is obsolete
