### ISSUE TITLE
mmt make pdflatex should require localpaths.tex

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#470]
If I remember correctly,  currently only the `alltex` target makes `localpaths.tex` (and some others), but at least the `pdflatex` and `allpdf`  targets should do so as well. There may be more. 
We should think about a new target that makes these files and call that wherever necessary.

**Comment by lambdaTotoro** [comment]
This was solved along with #515, hence I'll close this. If I missed some target, please feel free to let me know.
