### ISSUE TITLE
jperp and jbot seem to elaborate to the same unicode

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#478]
`jperp` should be U+27C2
`jbot` should be U+22A5
cc: @Jazzpirate

**Comment by florian-rabe** [comment]
I've changed it.

@kohlhase The info is stored in the file
https://github.com/UniFormal/MMT
devel/src/mmt-api/resources/unicode/unicode-latex-map
which you can edit safely if you need more Unicode symbols in the future.

You need to reinstall the MMT plugin afterwards to make the change visible to jEdit.
Not sure what to do for intelliJ.
