### ISSUE TITLE
another sms dependency

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#490]
sms generation needs to take into account the following case as well:
```
\begin{mhview}[frompath=search/en/problem-formulation]{problem-formulation}{search-problem}
```
example from `MathHub/MiKoMH/AI/source/search/en/search-problem`
This must make `MathHub/MiKoMH/AI/source/search/en/problem-formulation.sms`. Similarly, if the `topath` option is given then `.../search-problem.sms` must be given (unless  -- as in this case -- we are in the file already). 

And for the `{view}` environment as well. There the attributes are `loadfrom` and `loadto`.

**Comment by lambdaTotoro** [comment]
This became irrelevant with the deprecation of the sms format (see #551). Closing.
