### ISSUE TITLE
sTeX build broken: \importmhmodule extended syntax needed for sms

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#499]
I have introduced `\importmhmoudle[dir=foo]{bar}` as an abbreviation for `\importmhmodule[path=foo/bar]{bar}` and the same for `\usemhmodule`.  
And generally, `repos=` is now `mhrepos=`.

NOTE: the old form is also still valid.

BUT I did not realize that this disrupts the sTeX building, in particular `sms` creation. 
@lambdaTotoro could you have a look (soon).

**Comment by kohlhase** [comment]
My problem is that I will need to have the sTeX functionality back on tuesday when I have the next lecture. Sorry.

**Comment by lambdaTotoro** [comment]
This should be fixed as of 2c4fc20. That commit now treats `dir=` options correctly for ´\usemhmodule´ and `\importmhmodule` and looks for both `repos` and `mhrepos`.

It also allows for `\mhinputref*` (not just `\mhinputref`) as discussed.
