### ISSUE TITLE
new mmt make target localpaths

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#515]
Often we only use `mmt make alltex` to generate the file `localpath.tex` in a directory (see #514)
There should be a separate target `localpaths` for that, which is called in `mmt make alltex` and in other targets like `mmt make pdflatex` as well (it currently is not, and that is a bit annoying). 

Intended behavior: `mmt make localpath` should generate the file `localpath.tex` in the local directory. The contents can stay the same as they are currently.

**Comment by Jazzpirate** [comment]
I use ```mmt make sms``` to generate ```localpath.tex``` which works fine for me, if that helps

**Comment by kohlhase** [comment]
ah, interesting. but I still think that generating localpaths should be separate. 
BUT also see https://github.com/slatex/sTeX/issues/258 (I would like to get rid of the `localpaths.tex` file, but have not quite managed this).

**Comment by lambdaTotoro** [comment]
I've added a target for this as of commit f1fb950, `mmt make localpaths` now creates that file. All the other relevant targets (`make alltex`, `make sms`, ...) now depend on that.

Please test this functionality to see if I missed anything. Feel free to reopen if there are any problems.

**Comment by kohlhase** [comment]
it seems that `mmt make localpaths --force` does not re-create existing files, though in my understanding it should. 
ALSO, it would be nice, if `mmt make localpaths` would only create the file `localpaths.tex` in a directory if there is a sister `*.tex` file.

**Comment by lambdaTotoro** [comment]
Done and done, as of commit e87a7641b7b17f18158323f0a993a7ef14347993.
