### ISSUE TITLE
mmt make pdflatex should have localpaths as a dependency

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#523]
It seems that `mmt make pdflatex foo.tex` does not make the necessary `localpaths.tex` in the respective directory.

**Comment by kohlhase** [comment]
ooops, why was this closed? reopening
This also applies to the other `pdflatex`-like build targets, like `alltex`, `allpdf`, ...

**Comment by lambdaTotoro** [comment]
I looked into this and it is a strange thing indeed.
Because the dependency _is_ there, correctly generated, the same way it is being generated in `alltex` or `allpdf`. 

But, like with issue #500, somehow it is not being build. I'll keep at it.

**Comment by kohlhase** [comment]
this may be invalidated by #540

**Comment by lambdaTotoro** [comment]
I think the part that isn't invalidated by #540 is already present in #500. Closing.
