### ISSUE TITLE
get rid of localpaths

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#540]
The newest sTeX does not rely on the `localpaths.tex` files any more, we can 
* deprecate the build target (to delete it in the future) 
* and in particular not invoke it any more (e.g in `mmt make pdflatex`)
* not generate any `\input{localpaths}` in (e.g. in `make alltex` and the modules wrapper of `make pdflatex`)

in particular the last part is a problem; I am eliminating all of the `\input{localpaths}` from MathHub.

**Comment by lambdaTotoro** [comment]
I have deprecated the build target and removed all the invocations, but I honestly cannot find the place(s) in the MMT codebase where any `\input{localpaths}` would be generated. Is that something we know still happens?

**Comment by kohlhase** [comment]
I think that might be in the generation of all.*.tex (i.e. the `alltex` target)

**Comment by kohlhase** [comment]
I have to correct myself, that only copies `pre.*.tex` and I have removed localpaths from that. So I guess we are done.

**Comment by kohlhase** [comment]
Thanks a lot.

**Comment by kohlhase** [comment]
hmmm, I get a compilation error
```
[error] /Users/kohlhase/vc/git/github.com/UniFormal/MMT/src/mmt-stex/src/info/kwarc/mmt/stex/LaTeXML.scala:509:1: Missing closing brace `}' assumed here
[error] class PdfLatex extends LaTeXBuildTarget {
[error] ^
[error] one error found
```

**Comment by lambdaTotoro** [comment]
oops deleted a `}` too vigorously, try now.

**Comment by kohlhase** [comment]
seems to work now.
