### ISSUE TITLE
Check Documentation on Notation Tokens and Judgment Role Notation Generator

### ISSUE THREAD

**Issue by rappatoni** [UniFormal/MMT#541]
Please double-check the addition I made [hre](https://github.com/UniFormal/uniformal.github.io/blob/master/doc/language/declarations.md).
	
Also, if there are any more notation tokens of the kind %\<argument\>\<argument\> besides the ones I mentioned there, we should document them.

**Comment by florian-rabe** [comment]
It loos OK.

There are a few more - they can be seen in the documentation of the source code for the parser - NotationComponents.scala, function Marker.parse.

**Comment by ComFreek** [comment]
See #516 for a compilation of notation syntax.
