### ISSUE TITLE
frameit module fails to compile

### ISSUE THREAD

**Issue by tkw1536** [UniFormal/MMT#547]
On the tests, the docker build, and my local machine, the frameit module fails to compile. See [the logs](https://github.com/UniFormal/MMT/runs/1268860542#step:5:656). This regression was introduced in 890646a8bf209205108b7255ac6b7114a3da628b. 

This failure blocks the `mmt.jar` from being built and the tests from being run. 
We should do one of the following:
- fix the frameit module or
- undo the change that caused this problem or
- remove the frameit module from the mmt.jar.

**Comment by ComFreek** [comment]
I was now able to reproduce the issue in IntelliJ - after clearing my old build caches. Somehow they were inconsistent allowing IntelliJ to compile and run FrameIT.

In the referenced commit above, I made it at least compile, albeit it will fail on runtime for the FrameIT module. This will only affect me and John.
