### ISSUE TITLE
Raise an error when two archives with the same id are opened

### ISSUE THREAD

**Issue by tkw1536** [UniFormal/MMT#549]
/cc @lambdaTotoro @florian-rabe

**Comment by ComFreek** [comment]
https://github.com/UniFormal/MMT/commit/5c83fc9b5757eaf9a186857cade116041914f29b should have fixed it, no?

**Comment by ComFreek** [comment]
Oh, actually not. That commit was to `devel-names`. (Until someone `git cherrypick`s this commit to `devel`, I'll reopen.)

**Comment by lambdaTotoro** [comment]
Yes, see the comment I left on the commit. It also prints the root of the _new_ archive, while the error message indicates that it would be the old one.

**Comment by florian-rabe** [comment]
fixed

**Comment by ComFreek** [comment]
The fix was again on `devel-names`. I `git cherry-pick`ed the two commits related to this issue to `devel` now.
