### ISSUE TITLE
mmt make alltex no longer works

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#561]
I on the `sTeX` branch I get 
```
kohlhase@MiKo source % mmt make alltex
user: 'make alltex'
  error: build target not found: alltex
```
@Jazzpirate did you get rid of this? 

This may or may not be related to #560

**Comment by Jazzpirate** [comment]
...looks like some things in mmt-stex were needed after all -.-

what does alltex do? pdflatex on every tex file?

**Comment by kohlhase** [comment]
No, in a directory makes a file `all.tex` that `\input`s all sTeX files in that dir topologically sorted by dependency. Very useful for testing. 

Also `mmt make pdflatex` (which runs pdflatex over all files)  and `mmt make allpdf` makes `alltex` and runs pdflatex over it are somewhat useful.

**Comment by Jazzpirate** [comment]
okay, what this means is that for now you can just switch to the devel branch of MMT (rather than the sTeX branch), and everything should work there.

Then I'll need to find out how the alltex build target determines the dependency order - heuristically by hardcoding all "import"-like commands, I guess?

**Comment by kohlhase** [comment]
unfortunately, the devel branch does not build for me :-( (no matter, not important for the moment).

**Comment by kohlhase** [comment]
For the dependency order and `mmt make alltex` you should ask @lambdaTotoro

**Comment by Jazzpirate** [comment]
Yeah, I looked at the code, and it looks like all dependency macros are hardcoded. In the long term, we probably want to use latexml-generated annotations instead.

**Comment by kohlhase** [comment]
that may very well be.

**Comment by Jazzpirate** [comment]
...in the short time, I will restore the build targets on the sTeX branch as well (also, figure out why apparently devel doesn't compile?)

**Comment by kohlhase** [comment]
> also, figure out why apparently devel doesn't compile?)

sorry, after a `sbt clean` it does. I keep forgetting; sorry.

**Comment by lambdaTotoro** [comment]
> Then I'll need to find out how the alltex build target determines the dependency order

As @kohlhase already mentioned, that's done topologically by dependency, see [this file](https://github.com/UniFormal/MMT/blob/master/src/mmt-api/src/main/info/kwarc/mmt/api/archives/Relational.scala) and #519. The dependency map (i.e. what needs what) is generated [here](https://github.com/UniFormal/MMT/blob/master/src/mmt-api/src/main/info/kwarc/mmt/api/archives/BuildTarget.scala#L682-L699).

Please let me know if I can help out, but I think I'll switch the assignment on this.

**Comment by Jazzpirate** [comment]
pushed sTeX branch; BuildTargets alltex, tex-deps, pdflatex and tikzsvg have been restored for now
