### ISSUE TITLE
Loading Isabelle on MathHub seems to cause an infinite loop

### ISSUE THREAD

**Issue by tkw1536** [UniFormal/MMT#562]
When loading the Isabelle archives on MathHub, this seems to prevent MMT from doing anything. 

In particular, the server seems to run into an infinite loop and not do anything anymore. 
I am not sure if this is a core MMT issue (of scaling) or a MathHub specific issue.  
I will investigate this and document the results in this issue.

**Comment by Jazzpirate** [comment]
Can you explain what you mean by "loading the archives"?

Do you mean reading the relational files or actively retrieving content (e.g. to present it somewhere)?

**Comment by tkw1536** [comment]
"loading the archive" means "archive add" followed by trying to get the narrative root document of the archive

**Comment by Jazzpirate** [comment]
:O That seems.... highly inlikely. Both of those only entail "reading the MANIFEST.MF"...??

**Comment by Jazzpirate** [comment]
oh wait - what do you mean by "getting the narrative root document"? Like, the narrative root is just a DPath in the MANIFEST.MF. There does not need to exist an actual *document* with that URI... which one is it in your case?

**Comment by tkw1536** [comment]
I do mean `.get`ing that DPath.  The document is generated dynamically somewhere inside `mmt-api`, and this works perfectly fine for other archives. It typically only contains references to all `.omdoc` files in the archive.

**Comment by Jazzpirate** [comment]
> 
> 
> I do mean `.get`ing that DPath. The document is generated dynamically somewhere inside `mmt-api`, and this works perfectly fine for other archives. It typically only contains references to all `.omdoc` files in the archive.

Ooooh! I did not know that. In that case it is *very* possible that MMT doesn't run in an infinite loop, but rather runs for quite a while, and possibly runs into memory-exceptions. The AFP archive is *massive*, and if generating that document requires loading *all archive content*, that might be an issue... (or there are content errors with some of the content, of course...) do you have a log file or something? And if so does that log "debug" (i.e. all exceptions and errors with full stack trace)?

**Comment by tkw1536** [comment]
Figured out where this came from. This was caused by trying to load statistics for the archive. That tried to recursively load the entire archive. 

I've build a workaround that only enables statistics if the "statistics" key in manifest.mf is set to true.
